### ISSUE TITLE
Perform compliance checks for simplified tax invoice

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#100]
When I perform compliance checks for simplified tax invoice with sync Batch I get the below Error

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 220, in execute_job
    retval = method(**kwargs)
      site = '*****************'
      method = <function _perform_compliance_checks at 0x7f95fbb73600>
      event = None
      job_name = 'ksa_compliance.compliance_checks._perform_compliance_checks'
      kwargs = {'business_settings_id': 'AA-Saudi Arabia-SAR', 'simplified_customer_id': 'Palmer Productions Ltd.', 'standard_customer_id': '', 'item_id': 'SKU002', 'tax_category_id': 'VAT'}
      user = 'Administrator'
      is_async = True
      retry = 0
      retval = None
      method_name = 'ksa_compliance.compliance_checks._perform_compliance_checks'
      before_job_task = 'frappe.monitor.start'
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 65, in _perform_compliance_checks
    simplified_result = _perform_compliance_for_invoice_type(progress, progress_per_step, ft('Simplified'),
      business_settings_id = 'AA-Saudi Arabia-SAR'
      simplified_customer_id = 'Palmer Productions Ltd.'
      standard_customer_id = ''
      item_id = 'SKU002'
      tax_category_id = 'VAT'
      num_steps = 9
      progress_per_step = 11.11111111111111
      progress = 0.0
      settings = <ZATCABusinessSettings: AA-Saudi Arabia-SAR>
      simplified_result = None
      standard_result = None
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 96, in _perform_compliance_for_invoice_type
    invoice = _make_invoice(settings.company, customer_id, item_id, tax_category_id)
      progress = 0.0
      progress_per_step = 11.11111111111111
      invoice_type = 'Simplified'
      customer_id = 'Palmer Productions Ltd.'
      settings = <ZATCABusinessSettings: AA-Saudi Arabia-SAR>
      item_id = 'SKU002'
      tax_category_id = 'VAT'
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 174, in _make_invoice
    invoice.save()
      company = 'AA'
      customer = 'Palmer Productions Ltd.'
      item = 'SKU002'
      tax_category_id = 'VAT'
      invoice = <SalesInvoice: ACC-SINV-2024-00007>
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
      self = <SalesInvoice: ACC-SINV-2024-00007>
      args = ()
      kwargs = {}
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
      self = <SalesInvoice: ACC-SINV-2024-00007>
      ignore_permissions = None
      ignore_version = None
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
      self = <SalesInvoice: ACC-SINV-2024-00007>
      ignore_permissions = None
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
      self = <SalesInvoice: ACC-SINV-2024-00007>
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <SalesInvoice: ACC-SINV-2024-00007>
      method = 'validate'
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x7f95f96ddb20>
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
      self = <SalesInvoice: ACC-SINV-2024-00007>
      args = ()
      kwargs = {}
      hooks = [<function validate_accounting_period_on_doc_save at 0x7f95fa6123e0>, <function validate_sales_invoice at 0x7f95f95723e0>, <function apply at 0x7f95f91ca160>, <function check_for_running_deletion_job at 0x7f95f91cbd80>]
      method = 'validate'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      handler = 'erpnext.setup.doctype.transaction_deletion_record.transaction_deletion_record.check_for_running_deletion_job'
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f95f91cbce0>
      compose = <function Document.hook.<locals>.compose at 0x7f95f919aac0>
      f = <function Document.run_method.<locals>.fn at 0x7f95f96ddb20>
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
      self = <SalesInvoice: ACC-SINV-2024-00007>
      method = 'validate'
      args = ()
      kwargs = {}
      f = <function validate_sales_invoice at 0x7f95f95723e0>
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f95f93f4e00>
      fn = <function Document.run_method.<locals>.fn at 0x7f95f96ddb20>
      hooks = (<function validate_accounting_period_on_doc_save at 0x7f95fa6123e0>, <function validate_sales_invoice at 0x7f95f95723e0>, <function apply at 0x7f95f91ca160>, <function check_for_running_deletion_job at 0x7f95f91cbd80>)
  File "apps/ksa_compliance/ksa_compliance/standard_doctypes/sales_invoice.py", line 110, in validate_sales_invoice
    raise frappe.ValidationError()
      self = <SalesInvoice: ACC-SINV-2024-00007>
      method = 'validate'
      valid = False
      is_phase_2_enabled_for_company = True
frappe.exceptions.ValidationError:

**Comment by mhaggag** [comment]
Is the output clipped? Can you share what the message of the validation error is? (Last line)
Or is the exception in this case thrown without an error?

**Comment by saud-2** [comment]
without any error details.
the first unit standard invoice with sync live is done with no issue.
this is the second unit simplified invoice with sync batch

**Comment by mhaggag** [comment]
I looked and found that we had made a fix for the blank error message on `develop` in #78, which is not merged to master yet. This error is getting thrown when validating the sales invoice before preparing the ZATCA submission. It validates two things:
1) The invoice has a tax category set
2) The invoice has taxes applied

Given that compliance lets you choose a tax category and sets it, the error is likely coming from the lack of taxes. Meaning, something in the configuration is causing the generated invoice to not calculate/apply taxes. Can you create a sales invoice manually with the same configuration (company, item, customer, tax category) and check whether the draft invoice includes tax?

**Comment by saud-2** [comment]
you are right . I forgot to create Sales Taxes and Charges Template.

Thank you

**Comment by mhaggag** [comment]
No worries. We also have another fix on `develop` from #87 that should surface these errors during compliance for a better user experience, so that it's much clearer what went wrong and how to fix it.

**Comment by saud-2** [comment]
Appreciate your efforts.
