### ISSUE TITLE
 "warnings": [     {       "category": "KSA",       "code": "BR-KSA-80",       "message": " The Pre-Paid amount (BT-113) must be equal to the sum total of the Prepayment VAT category Taxable Amount (KSA-31) and the Prepayment VAT Category Tax Amount (KSA-32)."     }   ],

### ISSUE THREAD

**Issue by alaalsalam** [lavaloon-eg/ksa_compliance#101]
"warnings": [
    {
      "category": "KSA",
      "code": "BR-KSA-80",
      "message": " The Pre-Paid amount (BT-113) must be equal to the sum total of the Prepayment VAT category Taxable Amount (KSA-31) and the Prepayment VAT Category Tax Amount (KSA-32)."
    }
  ],

![image](https://github.com/user-attachments/assets/10972674-8f48-429f-b878-de76872e007c)

**Comment by mhaggag** [comment]
Thanks for the report.

This is the same as #99 ([comment](https://github.com/lavaloon-eg/ksa_compliance/issues/99#issuecomment-2312456100)), for which we have a fix under testing in the `develop` brnach

**Comment by mhaggag** [comment]
I'll close this so we have one issue to track this: #99
