### ISSUE TITLE
Errors and Warnings

### ISSUE THREAD

**Issue by MTAS101** [lavaloon-eg/ksa_compliance#112]
hello sir 
it is report after send invoice to zatca

Messages
[XSD] validation result : PASSED
[EN] validation result : PASSED
[KSA] validation result : PASSED
[QR] validation result : PASSED
[SIGNATURE] validation result : PASSED
[PIH] validation result : PASSED
validation_messages
Errors and Warnings
en validation warnings : 
CODE : BR-CL-14, MESSAGE : [BR-CL-14]-Country codes in an invoice MUST be coded using ISO code list 3166-1
validation_errors

if me check by xml in zatck site in the link 

https://sandbox.zatca.gov.sa/Compliance

Validation XML
ACC-SINV-2024-00018-AdditionalFields-22.xml
Valid : false
Errors
category : SIGNATURE_ERROR
code :X509IssuerName
message : wrong X509IssuerName  
category : SIGNATURE_ERROR
code :X509SerialNumber
message : wrong X509SerialNumber  
Warnings
category : BR_WARNING
code :BR-CL-14
message : يجب ترميز رموز البلدان في الفاتورة باستخدام قائمة رموز ISO 3166-1

sample from invoice
[ACC-SINV-2024-00018-AdditionalFields-22.zip](https://github.com/user-attachments/files/16883940/ACC-SINV-2024-00018-AdditionalFields-22.zip)

**Comment by omarashrafsarhan** [comment]
The problem is in the country code in this tag
<cac:Country>
<cbc:IdentificationCode>sa</cbc:IdentificationCode>
</cac:Country>

You need only to change it as per the standard codes of "ISO 3166-1"

Open the country record and you will find the country code field change it to "SA" and it will work

**Comment by MTAS101** [comment]
Thanks fix problem

> Open the country record and you will find the country code field change it to "SA" and it will work
