### ISSUE TITLE
Zatca integration summary and details report

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#115]
Dears,
1-  Is it possible to have the report for all companies (consolidated ) in addiction to specific company.
2- I noticed that the summary and details report doesn't show POS invoices.

Thank you.

**Comment by omarashrafsarhan** [comment]
First, I want to express my appreciation for your thorough effort and valuable input. As you are aware, we can address requests like this either through direct communication or based on community demand.

While I can assure you that this suggestion will be added to our backlog, I cannot provide a specific timeline for when it will be implemented.

Thank you again for your understanding and contribution. I will now proceed to close this issue, but please don’t hesitate to reach out for any further questions or clarifications.
