### ISSUE TITLE
Incorrect Handling of Customer Identification for B2B Invoices

### ISSUE THREAD

**Issue by omarashrafsarhan** [lavaloon-eg/ksa_compliance#123]
The system is incorrectly requiring both the VAT Registration Number and an additional ID for customers in B2B invoices. As per ZATCA guidelines, only one identification method should be required—either the VAT Registration Number (if available) or another buyer ID (when the VAT Registration Number is not available).

**Preconditions**
The company must have ZATCA business settings with type B2B only
The selected customer must have additional ID without VAT number
**Repro Steps**

1. Create sales invoice for this company
2. Select customer with additional Id only
3. Select the item
4. Save then submit

**Actual results**

- The system currently mandates that both the VAT Registration Number and another buyer ID be provided, even when the VAT Registration Number is not available
- The system depends on the identity of the B2B invoices based on the VAT Registration number

**Expected Results**

1. If the customer has a VAT Registration Number, the system should require only the VAT Registration Number.
2. If the customer does not have a VAT Registration Number, the system should accept other ID, without requiring the VAT Registration Number.
3. The system should be able to identify the B2B invoices based on the VAT number or the other buyer ID 
4. This change should be considered in the compliance checks

**Comment by mhaggag** [comment]
Fixed in 0.35.0
