### ISSUE TITLE
The additional seller IDs and the additional buyer IDs empty fields are considered in the XML

### ISSUE THREAD

**Issue by omarashrafsarhan** [lavaloon-eg/ksa_compliance#124]
The table of the additional seller ID and the additional buyer IDs are considered in the XML even if the fields doesn't have any value

**Preconditions**
Add more than on additional seller ID 
Add additional buyer ID

**Repro Steps**

1. Open ZATCA business setting one of the additional seller ID
2. Onboard the business setting again
3. Make compliance checks
4. Create sales invoice

**Actual results**

1. The removed additional ID still considered in the XML even it doesn't have value
2. This happens because the system consider the blank field and add it to the XML

**Expected Results**
We need to detect the blank field and replace it with null

**Comment by mhaggag** [comment]
Fixed in 0.35.0
