### ISSUE TITLE
Rejected - An unknown error occurred

### ISSUE THREAD

**Issue by infowaysa** [lavaloon-eg/ksa_compliance#126]
Good day,

A bit of background... 

After [https://github.com/lavaloon-eg/ksa_compliance/issues/119](url) had been resolved I managed to integrate with ZATCA. A problem happened with the server and I had to restore. Revoked the system from Fatoora portal. Setup everything back the way it was. Issued an OTP managed to get the CSR. Started testing and now Sandbox always getting approved but Simulation keeps giving "Rejected - An unknown error occurred"...

Any help would be much appreciated.

**Comment by infowaysa** [comment]
Never mind.... Figured out what the issue was... 
Feel free to close the issue.

Thanks and sorry.

**Comment by mhaggag** [comment]
No worries. Feel free to report any future issues, we really appreciate it.

**Comment by GienRose4** [comment]
Hi @infowaysa how did you resolve it? There is no clue for the error :(
![image](https://github.com/user-attachments/assets/22a0cd21-1d78-4281-a7e4-6b66af827fe3)
