### ISSUE TITLE
Zatca Phase2 -company not appear in Zatca

### ISSUE THREAD

**Issue by hamzaRuzmh** [lavaloon-eg/ksa_compliance#131]
I linked to the lavaloon Zatca application and the link was correct and the invoices appeared in accepted menu. But when I contacted the Zatca Authority and asked them if I was a link and the company appeared to them, they said no, I am not a link ,neither simulation nor product

can you please guide me

![WhatsApp Image 2024-09-26 at 11 38 19 AM](https://github.com/user-attachments/assets/5a3eee3b-d652-454a-b3ee-c42826688bf3)

**Comment by mhaggag** [comment]
Hello,

Is the `ZATCA Business Settings` for this company configured for Sandbox, Simulation, or Production?

**Comment by omarashrafsarhan** [comment]
Hello,

Please note that ZATCA dashboard and statistics is not working on ZATCA website until now, they still not finished yet with this page and dashboard so you can only rely on the API response you can find in "ZATCA integration log" doctype but for time being you can't review the submitted invoices on Fatoorah platform.

Here's a reference from ZATCA support regarding this issue [](https://zatca1.discourse.group/t/einvoice-statistics/1802)

**Comment by hamzaRuzmh** [comment]
Thank you for the clarification.

**Comment by omarashrafsarhan** [comment]
It's my pleasure, thank for choosing our app.

I'm proceeding with closing this issue now as long as it's clear to you, If you have any further question, please feel free to ask us.
