### ISSUE TITLE
ModuleNotFoundError: No module named 'pathvalidate'

### ISSUE THREAD

**Issue by infowaysa** [lavaloon-eg/ksa_compliance#134]
After updating to the latest version 0.35.0 I am we are getting this error.
Error first showed when trying to migrate the site after the update.
The app version appears to be 0.35.0 when checking under "About" and when trying to use the module anyway got the error:

> Server Error
>  
> ModuleNotFoundError: No module named 'pathvalidate'
> Possible source of error: ksa_compliance (app)

[ERROR ZATCA2 Update.txt](https://github.com/user-attachments/files/17185770/ERROR.ZATCA2.Update.txt)

**Comment by mhaggag** [comment]
The package was added to the app requirements (in pyproject.toml) in `0.33.0`. Please run `bench setup requirements --python`.

**Comment by infowaysa** [comment]
Thank you very much.
Just tested and it worked without issues.
