### ISSUE TITLE
Seller and buyer Address Warnings

### ISSUE THREAD

**Issue by BOTSolutions8686** [lavaloon-eg/ksa_compliance#140]
Hi . 
The buyer address is filled as per the instructions but the warnings are still appearing for both seller and customer. 
Any advice on the mater will be appreciated. 

Attached screenshots. 
<img width="1137" alt="Screenshot 2024-10-09 at 3 40 26 PM" src="https://github.com/user-attachments/assets/8081f688-8692-46b3-829e-1b2198c0f993">
<img width="1139" alt="Screenshot 2024-10-09 at 3 40 13 PM" src="https://github.com/user-attachments/assets/ff396f83-e15a-4584-9109-d01bba1c6950">

![WhatsApp Image 2024-10-09 at 09 41 52](https://github.com/user-attachments/assets/2866d904-7aeb-496f-a159-a057c9f76d8a)

**Comment by mhaggag** [comment]
Can you share the address parts in the generated XML from the `Sales Invoice Additional Fields`? They'll be under the `AccountingSupplierParty` and `AccountingCustomerParty` elements.

**Comment by BOTSolutions8686** [comment]
I can see that the Seller part data is not filled up on the xml 
But the buyer part is filled and is showing in xml 
<img width="896" alt="Screenshot 2024-10-11 at 5 01 45 PM" src="https://github.com/user-attachments/assets/5ecc7504-2455-486a-91f1-9d1a53f479eb">
<img width="897" alt="Screenshot 2024-10-11 at 5 01 14 PM" src="https://github.com/user-attachments/assets/db9ea1df-b28a-4a41-a941-290be721a938">


But the error message is both for buyer and seller.

**Comment by mhaggag** [comment]
For seller address, it looks like some elements are missing (hence the no such element errors in the corresponding elements). The seller address comes from the `ZATCA Business Settings` document associated with the company. If you update the address after configuring the business settings, you'll have to re-save the business settings (reselect the address, for example) to fetch the details again.

Not sure about the customer/buyer address. Can you check the buyer fields in the `Sales Invoice Additional Fields`? The customer address is captured in those fields when the additional fields document is created. Either the address wasn't there when it was created (on invoice submission), or the `customer_address` field on the sales invoice is not set.

**Comment by BOTSolutions8686** [comment]
Thank you very much for the detailed response . I will double check the information .

**Comment by BOTSolutions8686** [comment]
The issue can be closed . 
The problem was from our end and not the module. 
The seller address details needed to be updated in the module and not just company details.
