### ISSUE TITLE
What is wrong with this, I want to user Production: ZATCA production enviroment

### ISSUE THREAD

**Issue by alaalsalam** [lavaloon-eg/ksa_compliance#147]
Traceback with variables (most recent call last):
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 65, in _perform_compliance_checks
    simplified_result = _perform_compliance_for_invoice_type(progress, progress_per_step, ft('Simplified'),
      business_settings_id = 'Kayes Trading Establishment-Saudi Arabia-SAR'
      simplified_customer_id = 'Test Customer'
      standard_customer_id = 'test trilogy'
      item_id = '1001034'
      tax_category_id = 'Sales VAT Local 15%'
      num_steps = 18
      progress_per_step = 5.555555555555555
      progress = 0.0
      settings = <ZATCABusinessSettings: Kayes Trading Establishment-Saudi Arabia-SAR>
      simplified_result = None
      standard_result = None
      e = MandatoryError('[Sales Invoice, SINV-KTE-2024-00010]: sales_person, cost_center, department, selling_price_list, price_list_currency, plc_conversion_rate')
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 100, in _perform_compliance_for_invoice_type
    invoice = _make_invoice(settings.company, customer_id, item_id, tax_category_id)
      progress = 0.0
      progress_per_step = 5.555555555555555
      invoice_type = 'Simplified'
      customer_id = 'Test Customer'
      settings = <ZATCABusinessSettings: Kayes Trading Establishment-Saudi Arabia-SAR>
      item_id = '1001034'
      tax_category_id = 'Sales VAT Local 15%'
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 178, in _make_invoice
    invoice.save()
      company = 'Kayes Trading Establishment'
      customer = 'Test Customer'
      item = '1001034'
      tax_category_id = 'Sales VAT Local 15%'
      invoice = <SalesInvoice: SINV-KTE-2024-00010>
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
      self = <SalesInvoice: SINV-KTE-2024-00010>
      args = ()
      kwargs = {}
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
      self = <SalesInvoice: SINV-KTE-2024-00010>
      ignore_permissions = None
      ignore_version = None
  File "apps/frappe/frappe/model/document.py", line 292, in insert
    self._validate()
      self = <SalesInvoice: SINV-KTE-2024-00010>
      ignore_permissions = None
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 574, in _validate
    self._validate_mandatory()
      self = <SalesInvoice: SINV-KTE-2024-00010>
  File "apps/frappe/frappe/model/document.py", line 911, in _validate_mandatory
    raise frappe.MandatoryError(
      self = <SalesInvoice: SINV-KTE-2024-00010>
      missing = [('sales_person', 'Error: Value missing for Sales Invoice: Sales Person'), ('cost_center', 'Error: Value missing for Sales Invoice: Cost Center'), ('department', 'Error: Value missing for Sales Invoice: Department'), ('selling_price_list', 'Error: Value missing for Sales Invoice: Price List'), ('price_list_currency', 'Error: Value missing for Sales Invoice: Price List Currency'), ('plc_conversion_rate', 'Error: Value missing for Sales Invoice: Price List Exchange Rate')]
      d = <PaymentSchedule: unsaved parent=SINV-KTE-2024-00010>
      idx = 'plc_conversion_rate'
      msg = 'Error: Value missing for Sales Invoice: Price List Exchange Rate'
frappe.exceptions.MandatoryError: [Sales Invoice, SINV-KTE-2024-00010]: sales_person, cost_center, department, selling_price_list, price_list_currency, plc_conversion_rate

**Comment by mhaggag** [comment]
Compliance creates some invoices to submit to the ZATCA compliance API. It's running into an error because required fields are missing: sales_person, cost_center, department, selling_price_list, price_list_currency, plc_conversion_rate. 

For `selling_price_list` and related fields, please check whether a default price list is set in `Selling Settings`.

`cost_center` isn't required in standard ERPNext. Is this a customization, or is there a setting that makes it required?

I can't find `department` and `sales_person` fields on a standard v15 ERPNext instance. Are these custom fields, or from a different version?

**Comment by alaalsalam** [comment]
What about this error 


{"code":"Missing-ComplianceSteps","message":"The compliance certificate is not done with the following compliance steps yet [standard-compliant,standard-credit-note-compliant,standard-debit-note-compliant,simplified-compliant,simplified-credit-note-compliant,simplified-debit-note-compliant]"}

**Comment by mhaggag** [comment]
> What about this error
> 
> {"code":"Missing-ComplianceSteps","message":"The compliance certificate is not done with the following compliance steps yet [standard-compliant,standard-credit-note-compliant,standard-debit-note-compliant,simplified-compliant,simplified-credit-note-compliant,simplified-debit-note-compliant]"}

This is the production CSID API saying that you haven't completed the compliance steps, so you can't issue a production CSID yet. The compliance step must run successfully first. If the compliance errors above were caused by customizations, you can remove the "mandatory" flag on the fields in question, perform compliance, then restore the customization again.

**Comment by alaalsalam** [comment]
Thank you dear 😊
