### ISSUE TITLE
Rejected Invoice

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#151]
I have two invoices (same customer, same items, same amounts ) one is accepted the other one is rejected. 
tax include it .
What could be the reason?

**Comment by mhaggag** [comment]
Can you check the associated `Sales Invoice Additional Fields` for validation errors/warnings? If there aren't any, check the associated `ZATCA Integration Log` documents.

**Comment by saud-2** [comment]
[XSD] validation result : PASSED
[EN] validation result : FAILED
[KSA] validation result : FAILED
[QR] validation result : PASSED
[SIGNATURE] validation result : PASSED
[PIH] validation result : PASSED

en validation errors : 
CODE : BR-CO-15, MESSAGE : [BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).
CODE : BR-S-06, MESSAGE : [BR-S-06]-In a Document level allowance (BG-20) where the Document level allowance VAT category code (BT-95) is "Standard rated" the Document level allowance VAT rate (BT-96) shall be greater than zero.
CODE : BR-CO-14, MESSAGE : [BR-CO-14]-Invoice total VAT amount (BT-110) = Σ VAT category tax amount (BT-117).
en validation warnings : 
CODE : BR-S-05, MESSAGE : [BR-S-05]-For invoice items (BG-25) in which the VAT category code of invoiced items (BT-151) is "Standard rated" the VAT rate of the invoiced item (BT-152) must be greater than zero.
CODE : BR-S-08, MESSAGE : [BR-S-08]-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "Standard Rated", the VAT category taxable amount (BT-116) shall equal the sum of Invoice line net amounts (BT-131) minus the sum of Document level allowance amounts (BT-92) plus the sum of Document level charge amounts (BT-99) where the VAT category codes (BT-151, BT-95, BT-102) are "Standard Rate". and the VAT rates (BT-152,BT-96,BT-103) equal the VAT category rate (BT-119).
CODE : BR-CO-13, MESSAGE : [BR-CO-13]-Invoice total amount without VAT (BT-109) = Σ Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).
ksa validation errors : 
CODE : BR-KSA-84, MESSAGE : The Document level allowance VAT rate (BT-96), Document level Charge VAT rate (BT-103), VAT category rate(BT-119), Invoiced item VAT rate (BT-152), Prepayment VAT rate(KSA-34) must be limited to one of the following values (5 or 15) when the relevant Document level allowance VAT category code (BT-95), Document level Charge VAT category code(BT-102), VAT category code(BT-118), Invoiced item VAT category code(BT-151), Prepayment VAT Category Code (KSA-33) is "S"- "Standard rated". In other words, for Standard Rate VAT Category the rate can either be 15% or 5%.

**Comment by mhaggag** [comment]
We added in option in 0.29.0 to support blocking invoice submission if ZATCA validation fails. Please consider enabling it in `ZATCA Business Settings` to catch similar issues early in the future.

As to the error in this case, it looks like the kind of errors we see when rounding errors come up with tax included and/or discounts applied on grand total. Are you sure the invoices were identical in this case? If possible, please compare and/or share the generated XML files.

**Comment by saud-2** [comment]
sorry, after double check I found  items are diff. but same customer and same rates.

regarding blocking invoices, how I can enable it without enabling validate Generated XML because it is written that "This has a performance impact, so it's recommended to enable only for testing or troubleshooting problems"

**Comment by mhaggag** [comment]
> regarding blocking invoices, how I can enable it without enabling validate Generated XML because it is written that "This has a performance impact, so it's recommended to enable only for testing or troubleshooting problems"
Validation takes 1-3 seconds per invoice due to the Java startup time when invoking the CLI. If you're not producing invoices at a high rate (e.g. an invoice per second or similar), you can safely turn it on

> sorry, after double check I found items are diff. but same customer and same rates. below is rejected invoice xml.
> Details

The details are clipped. Can you edit out the sensitive details and attach the file or embed it in a code block?

**Comment by saud-2** [comment]
<details><summary>Details</summary>
<p>

<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2">
<ext:UBLExtensions>
<ext:UBLExtension>
<ext:ExtensionURI>urn:oasis:names:specification:ubl:dsig:enveloped:xades</ext:ExtensionURI>
<ext:ExtensionContent>
<sig:UBLDocumentSignatures xmlns:sig="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2" xmlns:sac="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2">
<sac:SignatureInformation>
<cbc:ID>urn:oasis:names:specification:ubl:signature:1</cbc:ID>
<sbc:ReferencedSignatureID>urn:oasis:names:specification:ubl:signature:Invoice</sbc:ReferencedSignatureID>
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="signature">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"/>
<ds:Reference Id="invoiceSignedData" URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
<ds:XPath>not(//ancestor-or-self::ext:UBLExtensions)</ds:XPath>
</ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
<ds:XPath>not(//ancestor-or-self::cac:Signature)</ds:XPath>
</ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
<ds:XPath>not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])</ds:XPath>
</ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>Rk1Vt3OlZinshvddKLPWt05MfKs0SbiUcJDGjQ7JbHg=</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="http://www.w3.org/2000/09/xmldsig#SignatureProperties" URI="#xadesSignedProperties">
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>NTBiMDI5ZjA4ODEzMjlhM2VlMGM3M2JmNzJlMTEwNzVmYThkODU5MGNhZTU0MWI1Y2I3NDczNzk4YjY3MjJlMA==</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>MEQCICGN2GAr4IOOAf8LGyAQ7IBPH15s0wLOmbD6ov/lxiOVAiBxGsKvZQJq7QHd0oDtVp5DQ7mS4ce19F3HpZILvkwDBg==</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZqVENDQlRLZ0F3SUJBZ0lURndBQWtDVk9aSk43WU5VMmNBQUJBQUNRSlRBS0JnZ3Foa2pPUFFRREFqQmlNUlV3RXdZS0NaSW1pWlB5TEdRQkdSWUZiRzlqWVd3eEV6QVJCZ29Ka2lhSmsvSXNaQUVaRmdObmIzWXhGekFWQmdvSmtpYUprL0lzWkFFWkZnZGxlSFJuWVhwME1Sc3dHUVlEVlFRREV4SlFVbHBGU1U1V1QwbERSVk5EUVRNdFEwRXdIaGNOTWpReE1ESXlNRGt5TkRVMFdoY05Namt4TURJeE1Ea3lORFUwV2pCbk1Rc3dDUVlEVlFRR0V3SlRRVEVjTUJvR0ExVUVDZ3dUMkxMWml0aXFJTmluMllUWmh0aXgyS3pZc3pFY01Cb0dBMVVFQ3d3VDJMTFppdGlxSU5pbjJZVFpodGl4Mkt6WXN6RWNNQm9HQTFVRUF3d1QyTExaaXRpcUlOaW4yWVRaaHRpeDJLellzekJXTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFLQTBJQUJJSFlKTm8yd1NKR09lWVJYN2s4a1QvQUIyMHl1WGtNdnFEM2VVSDhadGVPSVBJSmFSL2k1SEUrb3kvcEVuSWs0OEFTMlVPcXY5L21XTkdvUjBPWWhUK2pnZ1BETUlJRHZ6Q0NBU3dHQTFVZEVRU0NBU013Z2dFZnBJSUJHekNDQVJjeEd6QVpCZ05WQkFRTUVqRXRSVkpRVG1WNGRId3lMVEUxZkRNdE16RWZNQjBHQ2dtU0pvbVQ4aXhrQVFFTUR6TXhNREUyT1RJd01EWXdNREF3TXpFTk1Bc0dBMVVFREF3RU1URXdNREdCdGpDQnN3WURWUVFhRElHck56TTRNeURZcDltRTJMSFppdGluMkxZZ09pQTNNemd6SU5pMzJMSFppdG1DSU5pNTJLdlpoZGluMllZZzJLalpoaURZdWRtQjJLZlpoaUF0SU5pdDJZb2cyS2ZaaE5tRzJMSFlyTml6SU5pbjJZVFlzZG1GMkxJZzJLZlpoTmlvMkxIWml0aXYyWW9nTVRNek16WXRORFkzTUNEWXA5bUUyS3paaU5pbjJZUWdPaUF3TlRBMU5EUTBOVGs0TkRBc0lOaW4yWVRaaHRpeDJLellzeXdnMktmWmhOaXgyWXJZcDlpMk1ROHdEUVlEVlFRUERBWlNaWFJoYVd3d0hRWURWUjBPQkJZRUZGSUJ4dkhRSWwvQ2gwangvVmlMWVJqLzZWTnNNQjhHQTFVZEl3UVlNQmFBRkIvbG1OUW1HMlVabTltTHM3dnMvdUdubGp0Mk1JSGxCZ05WSFI4RWdkMHdnZG93Z2RlZ2dkU2dnZEdHZ2M1c1pHRndPaTh2TDBOT1BWQlNXa1ZKVGxaUFNVTkZVME5CTXkxRFFTZ3hLU3hEVGoxUVVscEZTVTVXVDBsRFJWTkRRVE1zUTA0OVEwUlFMRU5PUFZCMVlteHBZeVV5TUV0bGVTVXlNRk5sY25acFkyVnpMRU5PUFZObGNuWnBZMlZ6TEVOT1BVTnZibVpwWjNWeVlYUnBiMjRzUkVNOVpYaDBlbUYwWTJFc1JFTTlaMjkyTEVSRFBXeHZZMkZzUDJObGNuUnBabWxqWVhSbFVtVjJiMk5oZEdsdmJreHBjM1EvWW1GelpUOXZZbXBsWTNSRGJHRnpjejFqVWt4RWFYTjBjbWxpZFhScGIyNVFiMmx1ZERDQnpnWUlLd1lCQlFVSEFRRUVnY0V3Z2I0d2dic0dDQ3NHQVFVRkJ6QUNob0d1YkdSaGNEb3ZMeTlEVGoxUVVscEZTVTVXVDBsRFJWTkRRVE10UTBFc1EwNDlRVWxCTEVOT1BWQjFZbXhwWXlVeU1FdGxlU1V5TUZObGNuWnBZMlZ6TEVOT1BWTmxjblpwWTJWekxFTk9QVU52Ym1acFozVnlZWFJwYjI0c1JFTTlaWGgwZW1GMFkyRXNSRU05WjI5MkxFUkRQV3h2WTJGc1AyTkJRMlZ5ZEdsbWFXTmhkR1UvWW1GelpUOXZZbXBsWTNSRGJHRnpjejFqWlhKMGFXWnBZMkYwYVc5dVFYVjBhRzl5YVhSNU1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBOEJna3JCZ0VFQVlJM0ZRY0VMekF0QmlVckJnRUVBWUkzRlFpQmhxZ2RoTkQ3RW9idG5TU0h6dnNaMDhCVlpvZjZwV1dGMllRK0FnRmtBZ0VPTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNREJnZ3JCZ0VGQlFjREFqQW5CZ2tyQmdFRUFZSTNGUW9FR2pBWU1Bb0dDQ3NHQVFVRkJ3TURNQW9HQ0NzR0FRVUZCd01DTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDOVBTVFZ0NEF2ZXRyQ3cyTm92Q3pIM0ZrTkMrYk0yT3BWNW8yUnJuSVMvQUloQUxlUzJsVjRpdUFoMG5ya3h0OTVrZUplSEJJV2N1a3QxdFNDa0ZaSXpBQ08KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
<ds:Object>
<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Target="signature">
<xades:SignedProperties Id="xadesSignedProperties">
<xades:SignedSignatureProperties>
<xades:SigningTime>2024-10-22T13:06:11</xades:SigningTime>
<xades:SigningCertificate>
<xades:Cert>
<xades:CertDigest>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>ZGZjYjFiYzQzNGQyODJkMzhlZDk3MmI1OWNmNTU5NGY0OTQ0OWFjMTYzNTdkMjAyNmE2MmJlZTNlZjQyOWRmNQ==</ds:DigestValue>
</xades:CertDigest>
<xades:IssuerSerial>
<ds:X509IssuerName>CN=PRZEINVOICESCA3-CA, DC=extgazt, DC=gov, DC=local</ds:X509IssuerName>
<ds:X509SerialNumber>512917331168740705457783697213387556025045029</ds:X509SerialNumber>
</xades:IssuerSerial>
</xades:Cert>
</xades:SigningCertificate>
</xades:SignedSignatureProperties>
</xades:SignedProperties>
</xades:QualifyingProperties>
</ds:Object>
</ds:Signature>
</sac:SignatureInformation>
</sig:UBLDocumentSignatures>
</ext:ExtensionContent>
</ext:UBLExtension>
</ext:UBLExtensions>
<cbc:ProfileID>reporting:1.0</cbc:ProfileID>
<cbc:ID>ACC-SINV-ZN-2024-01245</cbc:ID>
<cbc:UUID>2b717527-ba93-47ba-bda8-f375879bd5ce</cbc:UUID>
<cbc:IssueDate>2024-10-22</cbc:IssueDate>
<cbc:IssueTime>13:16:07</cbc:IssueTime>
<cbc:InvoiceTypeCode name="0200000">388</cbc:InvoiceTypeCode>
<cbc:DocumentCurrencyCode>SAR</cbc:DocumentCurrencyCode>
<cbc:TaxCurrencyCode>SAR</cbc:TaxCurrencyCode>
<cac:AdditionalDocumentReference>
<cbc:ID>ICV</cbc:ID>
<cbc:UUID>5</cbc:UUID>
</cac:AdditionalDocumentReference>
<cac:AdditionalDocumentReference>
<cbc:ID>PIH</cbc:ID>
<cac:Attachment>
<cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain">5AvXWcQ2BIXT6bpWVsFHvb5J5WWxGxcX3HYviTa+xek=</cbc:EmbeddedDocumentBinaryObject>
</cac:Attachment>
</cac:AdditionalDocumentReference>
<cac:AdditionalDocumentReference>
<cbc:ID>QR</cbc:ID>
<cac:Attachment>
<cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain">ARPYstmK2Kog2KfZhNmG2LHYrNizAg8zMTAxNjkyMDA2MDAwMDMDEzIwMjQtMTAtMjJUMTM6MTY6MDcEBTI0MC4wBQQzMS4zBixSazFWdDNPbFppbnNodmRkS0xQV3QwNU1mS3MwU2JpVWNKREdqUTdKYkhnPQdgTUVRQ0lDR04yR0FyNElPT0FmOExHeUFRN0lCUEgxNXMwd0xPbWJENm92L2x4aU9WQWlCeEdzS3ZaUUpxN1FIZDBvRHRWcDVEUTdtUzRjZTE5RjNIcFpJTHZrd0RCZz09CFgwVjAQBgcqhkjOPQIBBgUrgQQACgNCAASB2CTaNsEiRjnmEV+5PJE/wAdtMrl5DL6g93lB/GbXjiDyCWkf4uRxPqMv6RJyJOPAEtlDqr/f5ljRqEdDmIU/CUgwRgIhAL09JNW3gC962sLDY2i8LMfcWQ0L5szY6lXmjZGuchL8AiEAt5LaVXiK4CHSeuTG33mR4l4cEhZy6S3W1IKQVkjMAI4=</cbc:EmbeddedDocumentBinaryObject>
</cac:Attachment>
</cac:AdditionalDocumentReference>
<cac:Signature>
<cbc:ID>urn:oasis:names:specification:ubl:signature:Invoice</cbc:ID>
<cbc:SignatureMethod>urn:oasis:names:specification:ubl:dsig:enveloped:xades</cbc:SignatureMethod>
</cac:Signature>
<cac:AccountingSupplierParty>
<cac:Party>
<cac:PartyIdentification>
<cbc:ID schemeID="CRN"> xxxxxxxxxxxx</cbc:ID>
</cac:PartyIdentification>
<cac:PostalAddress>
<cbc:StreetName>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</cbc:StreetName>
<cbc:BuildingNumber>xxxx</cbc:BuildingNumber>
<cbc:CitySubdivisionName>xxxxx</cbc:CitySubdivisionName>
<cbc:CityName>xxxxx</cbc:CityName>
<cbc:PostalZone>xxxxx</cbc:PostalZone>
<cac:Country>
<cbc:IdentificationCode>SA</cbc:IdentificationCode>
</cac:Country>
</cac:PostalAddress>
<cac:PartyTaxScheme>
<cbc:CompanyID>xxxxxxxxxxxx</cbc:CompanyID>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:PartyTaxScheme>
<cac:PartyLegalEntity>
<cbc:RegistrationName>xxxxxx</cbc:RegistrationName>
</cac:PartyLegalEntity>
</cac:Party>
</cac:AccountingSupplierParty>
<cac:AccountingCustomerParty>
<cac:Party>
<cac:PostalAddress>
<cbc:PostalZone>xxxxxx</cbc:PostalZone>
</cac:PostalAddress>
<cac:PartyLegalEntity>
<cbc:RegistrationName>xxxxxxxxxxxxxxxxxxx</cbc:RegistrationName>
</cac:PartyLegalEntity>
</cac:Party>
</cac:AccountingCustomerParty>
<cac:AllowanceCharge>
<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
<cbc:AllowanceChargeReason>Discount</cbc:AllowanceChargeReason>
<cbc:Amount currencyID="SAR">0.0</cbc:Amount>
<cac:TaxCategory>
<cbc:ID>S</cbc:ID>
<cbc:Percent>0.0</cbc:Percent>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:TaxCategory>
<cac:TaxCategory>
<cbc:ID>S</cbc:ID>
<cbc:Percent>15.0</cbc:Percent>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:AllowanceCharge>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="SAR">31.3</cbc:TaxAmount>
<cac:TaxSubtotal>
<cbc:TaxableAmount currencyID="SAR">182.61</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="SAR">0.0</cbc:TaxAmount>
<cac:TaxCategory>
<cbc:ID>S</cbc:ID>
<cbc:Percent>0.0</cbc:Percent>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
<cac:TaxSubtotal>
<cbc:TaxableAmount currencyID="SAR">26.09</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="SAR">3.91</cbc:TaxAmount>
<cac:TaxCategory>
<cbc:ID>S</cbc:ID>
<cbc:Percent>15.0</cbc:Percent>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:TaxCategory>
</cac:TaxSubtotal>
</cac:TaxTotal>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="SAR">31.3</cbc:TaxAmount>
</cac:TaxTotal>
<cac:LegalMonetaryTotal>
<cbc:LineExtensionAmount currencyID="SAR">236.09</cbc:LineExtensionAmount>
<cbc:TaxExclusiveAmount currencyID="SAR">208.7</cbc:TaxExclusiveAmount>
<cbc:TaxInclusiveAmount currencyID="SAR">240.0</cbc:TaxInclusiveAmount>
<cbc:AllowanceTotalAmount currencyID="SAR">0.0</cbc:AllowanceTotalAmount>
<cbc:PayableAmount currencyID="SAR">240.0</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
<cac:InvoiceLine>
<cbc:ID>1</cbc:ID>
<cbc:InvoicedQuantity unitCode="PCE">6.0</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="SAR">210.0</cbc:LineExtensionAmount>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="SAR">0.0</cbc:TaxAmount>
<cbc:RoundingAmount currencyID="SAR">210.0</cbc:RoundingAmount>
</cac:TaxTotal>
<cac:Item>
<cbc:Name>xxxxxxxxxxxxxxxx</cbc:Name>
<cac:ClassifiedTaxCategory>
<cbc:ID>S</cbc:ID>
<cbc:Percent>0.0</cbc:Percent>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:ClassifiedTaxCategory>
</cac:Item>
<cac:Price>
<cbc:PriceAmount currencyID="SAR">210.0</cbc:PriceAmount>
<cbc:BaseQuantity unitCode="PCE">6.0</cbc:BaseQuantity>
<cac:AllowanceCharge>
<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
<cbc:Amount currencyID="SAR">270.0</cbc:Amount>
<cbc:BaseAmount currencyID="SAR">480.0</cbc:BaseAmount>
</cac:AllowanceCharge>
</cac:Price>
</cac:InvoiceLine>
<cac:InvoiceLine>
<cbc:ID>2</cbc:ID>
<cbc:InvoicedQuantity unitCode="PCE">1.0</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="SAR">26.09</cbc:LineExtensionAmount>
<cac:TaxTotal>
<cbc:TaxAmount currencyID="SAR">3.91</cbc:TaxAmount>
<cbc:RoundingAmount currencyID="SAR">30.0</cbc:RoundingAmount>
</cac:TaxTotal>
<cac:Item>
<cbc:Name>xxxxxxxxxxxxxxxxxxxx </cbc:Name>
<cac:ClassifiedTaxCategory>
<cbc:ID>S</cbc:ID>
<cbc:Percent>15.0</cbc:Percent>
<cac:TaxScheme>
<cbc:ID>VAT</cbc:ID>
</cac:TaxScheme>
</cac:ClassifiedTaxCategory>
</cac:Item>
<cac:Price>
<cbc:PriceAmount currencyID="SAR">26.09</cbc:PriceAmount>
<cbc:BaseQuantity unitCode="PCE">1.0</cbc:BaseQuantity>
</cac:Price>
</cac:InvoiceLine>
</Invoice>

</p>
</details>

**Comment by mhaggag** [comment]
Something wrong is happening with the first line--it's zero-rated so has no tax and coming up at 210 SAR (originally it was 270 and the rate was adjusted?). However, in tax totals per category, the 0% category is listed as having 0 tax amount (`cac:TaxTotal/cac:TaxSubtotal/cbc:TaxAmount`) but the taxable amount (`cac:TaxTotal/cac:TaxSubtotal/cbc:TaxableAmount`) is 182.61 not 210; it treated it as 15%, so tax is 27.39 and included in the 210. That's also why the `cac:TaxTotal/cbc:TaxAmount` is 31.3 (27.39 from line 1 + 3.91 from line 2)

If you confirm the above (line 1 with zero tax, line 2 with standard tax, any item or invoice-level discounts or rate edits), we can test the scenario and see if we can reproduce it

**Comment by saud-2** [comment]
both of items should be with standard tax 15% . 
Line one :  rate was 80 and edited for a customer to be 35 including tax  (give him discount ) =35*6(Quantity)=210 (tax =27.39 and taxable amount 182.61
Line two : rate was 20 and edited for a customer to be 30 including tax =30*1(Quantity) =30 (tax = 3.91 and taxable amount 26.09

**Comment by mhaggag** [comment]
Can you double check whether the item in line 1 has an item tax template? It's really weird that it would switch up the tax category from 15% to 0% for one line if it were defined at the invoice level.

**Comment by saud-2** [comment]
I don't use item tax template for items . I just use Sales Taxes and Charges Template as default and tax calculated on net total.

**Comment by saud-2** [comment]
I tried to issue credit note against rejected invoice but I got error that first item doesn't exist . I think there is something wrong with item itself not related to zatca app.
appreciate your support.
