### ISSUE TITLE
Zatca phase 2 invoice rejected

### ISSUE THREAD

**Issue by rizwan100mu** [lavaloon-eg/ksa_compliance#152]
Please help about this error
en validation warnings : 
CODE : BR-CL-14, MESSAGE : [BR-CL-14]-Country codes in an invoice MUST be coded using ISO code list 3166-1
signature validation errors : 
CODE : signatureValue, MESSAGE : wrong signature Value 

![Screenshot_20241024-185048](https://github.com/user-attachments/assets/fd95e547-a4c3-4a2f-9d3c-349cf1f15b7a)

**Comment by rizwan100mu** [comment]
Yes it is self hosted 
CLI before was manual but when I applied automatic and save after that Country code issue is fixed only now in signature error
CLI version 2.2.0
![17297921112662385675158675550734](https://github.com/user-attachments/assets/75727537-fee4-4452-9d97-de3fbee1746c)

ERPNext version is 15.38.4 version 15
KSA Compliance v0.37.7 master
![17297920457183378880688641845449](https://github.com/user-attachments/assets/d580b5e0-bde2-401a-a314-376fa0568a53)

**Comment by rizwan100mu** [comment]
Sorry I forgot to mention signature value in generated xml and it's has the value
![IMG_20241024_205647659](https://github.com/user-attachments/assets/1a835f31-d11d-40f3-b873-e00a2e2fe945)

**Comment by rizwan100mu** [comment]
How to find this log file

**Comment by mhaggag** [comment]
The log file is under your bench directory, inside `logs`. e.g. `/home/frappe/frappe-bench/logs/zatca.log`.

**Comment by rizwan100mu** [comment]
this currently onboarded as simulation and here find tha atached zatca log file
[zatca.txt](https://github.com/user-attachments/files/17533097/zatca.txt)

**Comment by mhaggag** [comment]
The error is generic, with no response from ZATCA shown:

```
2024-10-27 09:53:47,164 ERROR zatca An HTTP error occurred: ReportOrClearInvoiceError(response='', error='An unknown error occurred')
```

* Can you share `bench version` output or `Help -> About` from Desk?
* Did you complete the onboarding steps? (Generate CSR, then perform compliance, then get production CSID)

**Comment by mhaggag** [comment]
I'm closing this based on the other issue where you successfully were able to submit invoice. Please re-open if this is a different site that is still encountering an issue.
