### ISSUE TITLE
Error Importing Sales Invoices

### ISSUE THREAD

**Issue by EmkanDevs** [lavaloon-eg/ksa_compliance#154]
Hello,

Having an issue when trying to import sales invoices. Didn't have the issue before installing the app.

Sample file:
[Sales Invoice_only submit - sample.xlsx](https://github.com/user-attachments/files/17519153/Sales.Invoice_only.submit.-.sample.xlsx)

Error received:

> Validation Error
> Please include tax rate in Sales Taxes and Charges Table
> Traceback (most recent call last):
>   File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 149, in import_data
>     doc = self.process_doc(doc)
>   File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 251, in process_doc
>     return self.insert_record(doc)
>   File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 270, in insert_record
>     new_doc.insert()
>   File "apps/frappe/frappe/model/document.py", line 291, in insert
>     self.run_before_save_methods()
>   File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
>     self.run_method("validate")
>   File "apps/frappe/frappe/model/document.py", line 962, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1322, in composer
>     return composed(self, method, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1306, in runner
>     add_to_return_value(self, f(self, method, *args, **kwargs))
>   File "apps/ksa_compliance/ksa_compliance/standard_doctypes/sales_invoice.py", line 129, in validate_sales_invoice
>     raise frappe.ValidationError(error_messages)
> frappe.exceptions.ValidationError: Please include tax rate in Sales Taxes and Charges Table

Thank you very much.

**Comment by EmkanDevs** [comment]
There's already a default Sales Taxes and Charges Template.

![opera_KdKtjlUJSr](https://github.com/user-attachments/assets/f312effb-c852-4491-a28a-dd1d763a69d5)

**Comment by mhaggag** [comment]
I tried the scenario locally, and the problem is that import expects you to set the contents of the sales taxes and charges table yourself (by providing the values in the Excel sheet). If I disable our validation temporarily, it creates an invoice that looks like this:

![image](https://github.com/user-attachments/assets/29109b36-161f-48fa-8b80-e5bb256e6688)

The sales taxes and charges table is only filled/calculated on Desk when you set/change the template. When I cleared the field on the invoice pictured above and set it again, it populated the taxes properly.

**Comment by EmkanDevs** [comment]
So what would be the work around in this case?
Could you please clarify on the steps we would need to follow?

Thank you.

**Comment by mhaggag** [comment]
You need to include the data for sales taxes and charges in the sheet. See the attached sheet for example.
[Sales Invoice(1).xlsx](https://github.com/user-attachments/files/17541661/Sales.Invoice.1.xlsx)

![image](https://github.com/user-attachments/assets/c477c3b8-ca56-4ee6-920b-34869ff7f742)

**Comment by EmkanDevs** [comment]
Thank you very much. It worked.
Much appreciated.
