### ISSUE TITLE
Invoice cancellation should be allowed for companies that don't have ZATCA phase 2 integration enabled

### ISSUE THREAD

**Issue by rizwan100mu** [lavaloon-eg/ksa_compliance#158]
I found 1 big issue after zatca integration sales invoice cant cancel the msg was coming of another company also You cannot cancel sales invoice according to ZATCA Regulations. if we have multiple company conditional logic to apply ZATCA restrictions only to the specific company which is configured in zatca setting not for all company

**Comment by mhaggag** [comment]
Hello,

You're right. We're working on a fix. We expect it to be merged into master today.

**Comment by rizwan100mu** [comment]
Please provide the file name and mark its code line where need to be modification in module

**Comment by mhaggag** [comment]
You can see the code changes in the PR linked in this issue. The fix is under testing and will be merged to master shortly.

**Comment by rizwan100mu** [comment]
and one thing also need to improve when if zatca configured as batch mode then it should be before the sync with zatca we can Cancel, Amed or delete any invoices

**Comment by mhaggag** [comment]
The fix is merged to master in 0.39.1

> Please implement this in ERPNext for ZATCA in batch mode, follow these steps to allow modification or delete before syncing and prevent canceled invoices from syncing

Cancellation, modification, and deletion is prohibited by ZATCA if integration is enabled regardless of mode. Please refer to this [comment](https://github.com/lavaloon-eg/ksa_compliance/issues/144#issuecomment-2428489924) for details and references.
