### ISSUE TITLE
Integration status: Rejected with An unknown error occurred

### ISSUE THREAD

**Issue by GienRose4** [lavaloon-eg/ksa_compliance#163]
Hi we are facing issue, but there is no clue for the error :(
![image](https://github.com/user-attachments/assets/b868de4e-a798-4393-9a0e-0bed04cf6cb3)

**Comment by GienRose4** [comment]
Hi this is fine now, we created simulation twice so maybe that is causing an issue. We just pushed with production

**Comment by mhaggag** [comment]
Hello. Did you get any error logs in the `Error Log` doctype when you tried this? They may contain extra details.

**Comment by GienRose4** [comment]
Hi @mhaggag, no extra details in error log.

**Comment by mhaggag** [comment]
Hmm. What about `ZATCA Integration Log`? We try to include the "raw" response returned by ZATCA there. If not, then `logs/zatca.log`.
