### ISSUE TITLE
ZATCA Validation Error Errors SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:string-length() ("CRN", "700") Warnings

### ISSUE THREAD

**Issue by Amirmansi** [lavaloon-eg/ksa_compliance#164]
ZATCA Validation Error
Errors
SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:string-length() ("CRN", "700")
Warnings

**Comment by mhaggag** [comment]
Hello

* Do you get this during compliance, or upon submitting invoices?
* What version of ksa_compliance do you have?

**Comment by AmirAhmed0s** [comment]
I get this during compliance, and upon submitting invoices
 
![لقطة شاشة 2024-11-07 090824](https://github.com/user-attachments/assets/4aae6bf6-ceac-49f2-9769-64f8b45db6fc)
![image](https://github.com/user-attachments/assets/b3d68dba-88ac-4246-8267-1743378f1108)

**Comment by AmirAhmed0s** [comment]
can you help and give me steps

**Comment by mhaggag** [comment]
I suspect it's a bug with multiple seller IDs in `ZATCA Business Settings` that was fixed in 0.34.0 and [0.35.0](https://github.com/lavaloon-eg/ksa_compliance/blob/master/CHANGELOG.md#0350). Can you update ksa_compliance to latest and check?
