### ISSUE TITLE
I get This Issue While Create Sales Invoice 

### ISSUE THREAD

**Issue by Amirmansi** [lavaloon-eg/ksa_compliance#165]
ZATCA Validation Error
Errors
SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:string-length() ("CRN", "700")
Warnings

**Comment by mhaggag** [comment]
Hello,

* Do you get this during compliance or when submitting an invoice after compliance?
* Can you share the output of `bench version`? (Or `Help -> About` from Desk)

**Comment by mhaggag** [comment]
Just noticed this is a duplicate of another issue #164, let's continue the discussion there.
