### ISSUE TITLE
Invoice printing does not support languages

### ISSUE THREAD

**Issue by tajff** [lavaloon-eg/ksa_compliance#166]

**Comment by mhaggag** [comment]
Hello,

The current print formats are indeed hard-coded to Arabic. I'll consult the business team and get back to you. I think it makes sense to have Arabic be the default, but the literal strings should be translated/translatable to different language using frappe's `_()` functions.

**Comment by BOTSolutions8686** [comment]
Hi. 
Maybe this will help

https://github.com/BOTSolutions8686/saudi_print_formats

**Comment by BOTSolutions8686** [comment]
We are also working on adding pdfa3(print format with embedded xml) to ksa_compliance 
Once done we will contribute it.

**Comment by mhaggag** [comment]
This was merged to the `develop` branch in #173 and will go through testing next week before going into master.

**Comment by mhaggag** [comment]
Merged to master in 0.39.3
