### ISSUE TITLE
When I try to create a new company then its getting issue with zatca

### ISSUE THREAD

**Issue by rizwan100mu** [lavaloon-eg/ksa_compliance#167]
When I try to create a new company then its getting issue with zatca its no need to be required for when creating any company
![image](https://github.com/user-attachments/assets/02c6fd84-4507-42e7-b990-e4caaaedbfd9)

**Comment by mhaggag** [comment]
We don't require it directly on the company. Unfortunately, ERPNext tries to add the company default account to the mode of payment and save it. When saving the mode of payment, it finds that the ZATCA payment means code is required (to be able to generate XML for invoices using that mode of payment), and fails.

Please update the modes of payment with the corresponding codes. See [this issue](https://github.com/lavaloon-eg/ksa_compliance/issues/153) for reference.
