### ISSUE TITLE
Rejected Invoice error

### ISSUE THREAD

**Issue by Yazan01H** [lavaloon-eg/ksa_compliance#169]
![Screenshot 2024-11-11 112944](https://github.com/user-attachments/assets/ac374204-8487-4190-a1f6-c64c6fed2897)
and 
![Screenshot 22](https://github.com/user-attachments/assets/6998a268-1302-4ff7-9c7c-edc3751a5124)

How can this error be resolved?

**Comment by mhaggag** [comment]
* For the decimal errors, we'll need to look at the XML. Can you share it after removing any sensitive information?
* For the bad signature error, that usually indicates something wrong with onboarding or the wrong Java runtime being used (any runtime greater than 11 results in the SDK signing code not finding the required elliptic curve cryptography)

**Comment by Yazan01H** [comment]
for the first img 
[SINV-iKSA-2024-0125-AdditionalFields-9.zip](https://github.com/user-attachments/files/17699666/SINV-iKSA-2024-0125-AdditionalFields-9.zip)

for second img 
[Rejected.zip](https://github.com/user-attachments/files/17699687/Rejected.zip)


Regarding the second point regarding the signature, what are the steps to solve it?

**Comment by Yazan01H** [comment]
Please provide us with the solution as soon as possible.

**Comment by mhaggag** [comment]
For the decimal errors, you have this in the generated invoice:
![image](https://github.com/user-attachments/assets/2748aacd-2f83-4108-9146-7be111848759)

Did you edit `ksa_compliance/ksa_compliance/templates/e_invoice.xml`? The [line](https://github.com/lavaloon-eg/ksa_compliance/blob/03781557a8b35e2b5ec0d1b124b167b61bb2a944/ksa_compliance/templates/e_invoice.xml#L173) that generates this tax total rounds to 2 decimal places. Also, ERPNext itself should round it on the invoice based on the configured system currency precision (which should be configured to 2 decimal places for ZATCA)

For signature validation, was it always failing for this company, or does it fail for some invoices only? Do you have other companies that pass signature validation? Did you change any company information after onboarding and production CSID? (VAT, CRN, etc.)

**Comment by Yazan01H** [comment]
![Screenshot 23](https://github.com/user-attachments/assets/56cc6d04-58ee-4d68-bbe2-6b9d9f307ecc)
No, I have not modified the file before.

All invoices, including those that are accepted, contain a signature validation warning.

**Comment by mhaggag** [comment]
Does the Sales Invoice itself contain the same value in its total field? With 4-digit precision?

Is this on sandbox, simulation, or production? The validation error shown for the signature is a local validation result using the ZATCA CLI (which in turn uses the SDK). If the ZATCA API accepts the invoice, it means the signature is valid from ZATCA's point of view. So, we need to understand why the local SDK thinks otherwise. Can you check the ZATCA CLI version and path? (In the CLI tab in ZATCA Business Settings)

**Comment by meaziz** [comment]
We are facing a similar issue ..

```
"errorMessages":[{"type":"ERROR","code":"BR-CO-15","category":"EN_16931","message":"Invoice total amount with VAT (BT-112) ","status":"ERROR"},{"type":"ERROR","code":"BR-CO-14","category":"EN_16931","message":"Invoice total VAT amount (BT-110) ","status":"ERROR"}]
```


```
 <cac:TaxTotal>
        <cbc:TaxAmount currencyID="SAR">163.73</cbc:TaxAmount>
            <cac:TaxSubtotal>
                <cbc:TaxableAmount currencyID="SAR">1091.5</cbc:TaxableAmount>
                <cbc:TaxAmount currencyID="SAR">163.72</cbc:TaxAmount>
                <cac:TaxCategory>
                    <cbc:ID>S</cbc:ID>
                    <cbc:Percent>15.0</cbc:Percent>
                    <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
                </cac:TaxCategory>
            </cac:TaxSubtotal>
    </cac:TaxTotal>
``` 



The Invoice total is 1,091.50 
Calculating the tax amount at 15% * 1,091.50  =  163.725 which is rounded to in ERPNext  The Total Taxes and Charges (SAR) on ERPNext Invoice field shows 163.73  
and the XML <cbc:TaxAmount currencyID="SAR">163.73</cbc:TaxAmount>

It appears to be a rounding issue when creating the tax category sum,
So a theorey is that the the Tax category calculation is rounded pre maturely (probably while being created)

But, checking the item-wise tax sum it adds up 81 + 27 + 32.40 + 10.73 + 12.60 = 163.73


| السلعة    | المبلغ الخاضع للضريبة | VAT 15%        |
|-----------|-----------------------|----------------|
| ITM-00198 | 540.00                | (15.0%) 81.00  |
| ITM-00448 | 180.00                | (15.0%) 27.00  |
| ITM-00414 | 216.00                | (15.0%) 32.40  |
| ITM-00013 | 71.50                 | (15.0%) 10.73  |
| ITM-00303 | 84.00                 | (15.0%) 12.60  |

https://github.com/lavaloon-eg/ksa_compliance/blob/03781557a8b35e2b5ec0d1b124b167b61bb2a944/ksa_compliance/output_models/e_invoice_output_model.py#L76


Any workarounds or other paths we can explore?

**Comment by meaziz** [comment]
We are facing a similar issue ..

```
"errorMessages":[{"type":"ERROR","code":"BR-CO-15","category":"EN_16931","message":"Invoice total amount with VAT (BT-112) ","status":"ERROR"},{"type":"ERROR","code":"BR-CO-14","category":"EN_16931","message":"Invoice total VAT amount (BT-110) ","status":"ERROR"}]
```


```
 <cac:TaxTotal>
        <cbc:TaxAmount currencyID="SAR">163.73</cbc:TaxAmount>
            <cac:TaxSubtotal>
                <cbc:TaxableAmount currencyID="SAR">1091.5</cbc:TaxableAmount>
                <cbc:TaxAmount currencyID="SAR">163.72</cbc:TaxAmount>
                <cac:TaxCategory>
                    <cbc:ID>S</cbc:ID>
                    <cbc:Percent>15.0</cbc:Percent>
                    <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
                </cac:TaxCategory>
            </cac:TaxSubtotal>
    </cac:TaxTotal>
``` 



The Invoice total is 1,091.50 
Calculating the tax amount at 15% * 1,091.50  =  163.725 which is rounded to in ERPNext  The Total Taxes and Charges (SAR) on ERPNext Invoice field shows 163.73  
and the XML <cbc:TaxAmount currencyID="SAR">163.73</cbc:TaxAmount>

It appears to be a rounding issue when creating the tax category sum,
So a theorey is that the the Tax category calculation is rounded pre maturely (probably while being created)

But, checking the item-wise tax sum it adds up 81 + 27 + 32.40 + 10.73 + 12.60 = 163.73


| السلعة    | المبلغ الخاضع للضريبة | VAT 15%        |
|-----------|-----------------------|----------------|
| ITM-00198 | 540.00                | (15.0%) 81.00  |
| ITM-00448 | 180.00                | (15.0%) 27.00  |
| ITM-00414 | 216.00                | (15.0%) 32.40  |
| ITM-00013 | 71.50                 | (15.0%) 10.73  |
| ITM-00303 | 84.00                 | (15.0%) 12.60  |

https://github.com/lavaloon-eg/ksa_compliance/blob/03781557a8b35e2b5ec0d1b124b167b61bb2a944/ksa_compliance/output_models/e_invoice_output_model.py#L76


Any workarounds or other paths we can explore?
