### ISSUE TITLE
line item tax rate and tax amount was not calculated 

### ISSUE THREAD

**Issue by meaziz** [lavaloon-eg/ksa_compliance#175]
For some reason the added invoice line item fields that was added as a workaround for the same item multiple lines / invoice are causing the XML to fail.

Errors
**BR-KSA-84**: The Document level allowance VAT rate (BT-96), Document level Charge VAT rate (BT-103), VAT category rate(BT-119), Invoiced item VAT rate (BT-152), Prepayment VAT rate(KSA-34) must be limited to one of the following values (5 or 15) when the relevant Document level allowance VAT category code (BT-95), Document level Charge VAT category code(BT-102), VAT category code(BT-118), Invoiced item VAT category code(BT-151), Prepayment VAT Category Code (KSA-33) is "S"- "Standard rated". In other words, for Standard Rate VAT Category the rate can either be 15% or 5%.

Image for line item (all are zeros):

<img width="524" alt="Screenshot 2024-11-18 at 2 42 19 PM" src="https://github.com/user-attachments/assets/4030aa9b-8c9f-4177-a2a6-c1674ab4f00a">

```
    <cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:AllowanceChargeReason>Discount</cbc:AllowanceChargeReason>
        <cbc:Amount currencyID="SAR">0.0</cbc:Amount>
            <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>0.0</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:TaxCategory>
    </cac:AllowanceCharge>
    <cac:TaxTotal>
        <cbc:TaxAmount currencyID="SAR">201.6</cbc:TaxAmount>
            <cac:TaxSubtotal>
                <cbc:TaxableAmount currencyID="SAR">1344.0</cbc:TaxableAmount>
                <cbc:TaxAmount currencyID="SAR">0.0</cbc:TaxAmount>
                <cac:TaxCategory>
                    <cbc:ID>S</cbc:ID>
                    <cbc:Percent>0.0</cbc:Percent>
                    <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
                </cac:TaxCategory>
            </cac:TaxSubtotal>
    </cac:TaxTotal>
    <cac:TaxTotal>
        <cbc:TaxAmount currencyID="SAR">201.6</cbc:TaxAmount>
    </cac:TaxTotal>
    <cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="SAR">1344.0</cbc:LineExtensionAmount>
        <cbc:TaxExclusiveAmount currencyID="SAR">1344.0</cbc:TaxExclusiveAmount>
        <cbc:TaxInclusiveAmount currencyID="SAR">1545.6</cbc:TaxInclusiveAmount>
        <cbc:AllowanceTotalAmount currencyID="SAR">0.0</cbc:AllowanceTotalAmount>
        <cbc:PayableAmount currencyID="SAR">1545.6</cbc:PayableAmount>
    </cac:LegalMonetaryTotal>
```
versions
ERPNext: v15.42.0 (HEAD)
Frappe Framework: v15.47.2 (HEAD)
KSA Compliance: v0.39.2 (HEAD)

**Comment by mhaggag** [comment]
Was this invoice issued before or after the fields were added? If this is an old invoice that you're trying to fix rejection for, the fields will unfortunately be initialized to zero. For such cases, they have to be fixed in the database.

**Comment by meaziz** [comment]
Thanks.
I'm not sure what may be the settings (if any) responsible for this.

This issue started after updating to the latest version.
The invoices are still in Draft (Newly) created after the update.

**Comment by mhaggag** [comment]
That is alarming. I reviewed the changelog for ERPNext releases from the version I was at locally (15.33.2) to 15.42.0 and found nothing relevant. I updated locally and tested a new invoice, but it's working fine for me.

```bash
~/erp-einvoice-test/apps/ksa_compliance [develop ≡]> bench version
erpnext 15.42.0
frappe 15.47.2
ksa_compliance 0.39.3
```

Is this on frappe cloud or self-hosted/local? If self-hosted, try to setup requirements and migrate just in case. The hook for calculating line-level tax information is still present in [erpnext/hooks.py](https://github.com/frappe/erpnext/blob/7c78e0025d37e081fe809459803b307492a477d2/erpnext/hooks.py#L578)

You can try to `bench console` and call `update_itemised_tax_data` on a draft invoice (it takes a sales invoice doc), then save and commit. See if it populates the values as expected. If it does, then the hook isn't being invoked. If it doesn't, then something broke the function itself or the way it calculates.

**Comment by meaziz** [comment]
The deployment is on Frappe Cloud.
The ksa_compliance **master** branch is on  0.39.2 not 0.39.3

**Comment by meaziz** [comment]
Thanks for pointing that out.
Apparently An End User took the liberty of changing the Country Name from "Saudi Arabia" to KSA which caused the regional setting not to take effect.

Closing this issue now.

But will appreciate your confirmation which branch should be used is it the master or develop branch?

**Comment by mhaggag** [comment]
> But will appreciate your confirmation which branch should be used is it the master or develop branch?

`master` is the stable branch that should be used for production and UAT. I'm on `develop` locally because that's what we use to write, review, and test new features and fixes before merging them into `master`.
