### ISSUE TITLE
_perform_compliance_checks

### ISSUE THREAD

**Issue by alaalsalam** [lavaloon-eg/ksa_compliance#179]
![image](https://github.com/user-attachments/assets/cbfda37c-4df5-42bc-b750-ccce87a26b4d)
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 162, in execute_job
    method(**kwargs)
      site = 'demoapp.site'
      method = <function _perform_compliance_checks at 0x7f7ea2162830>
      event = None
      job_name = '<function _perform_compliance_checks at 0x7f587f676b90>'
      kwargs = {'business_settings_id': 'شركة التأثير المزدوج للتجارة-Saudi Arabia-SAR', 'simplified_customer_id': 'شركة ثلاجة الخرج للتجارة', 'standard_customer_id': 'BASIC FITNESS GYM', 'item_id': 'Being 40% Advance Payment invoice against PO. 05_B1_05 Sindala Neom project', 'tax_category_id': '15%'}
      user = 'Administrator'
      is_async = True
      retry = 0
      method_name = '_perform_compliance_checks'
  File "apps/ksa_compliance/ksa_compliance/compliance_checks.py", line 163, in _perform_compliance_checks
    frappe.msgprint(
      business_settings_id = 'شركة التأثير المزدوج للتجارة-Saudi Arabia-SAR'
      simplified_customer_id = 'شركة ثلاجة الخرج للتجارة'
      standard_customer_id = 'BASIC FITNESS GYM'
      item_id = 'Being 40% Advance Payment invoice against PO. 05_B1_05 Sindala Neom project'
      tax_category_id = '15%'
      num_steps = 18
      progress_per_step = 5.555555555555555
      progress = 50.0
      has_error = True
      settings = <ZATCABusinessSettings: شركة التأثير المزدوج للتجارة-Saudi Arabia-SAR>
      simplified_result = _ComplianceResult(invoice_result='Invoice sent to ZATCA. Integration status: Accepted', invoice_details='{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[],"errorMessages":[],"status":"PASS"},"reportingStatus":"REPORTED","clearanceStatus":null,"qrSellertStatus":null,"qrBuyertStatus":null}', credit_note_result='Invoice sent to ZATCA. Integration status: Accepted', credit_note_details='{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[],"errorMessages":[],"status":"PASS"},"reportingStatus":"REPORTED","clearanceStatus":null,"qrSellertStatus":null,"qrBuyertStatus":null}', debit_note_result='Invoice sent to ZATCA. Integration status: Accepted', debit_not...
      standard_result = _ComplianceResult(invoice_result='Invoice sent to ZATCA. Integration status: Accepted with warnings', invoice_details='{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[{"type":"WARNING","code":"BR-10","category":"EN_16931","message":"An Invoice shall contain the Buyer postal address (BG-8).Not applicable for simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02).","status":"WARNING"},{"type":"WARNING","code":"BR-KSA-F-06-C23","category":"KSA","message":"[BR-KSA-F-06-C23] - Field character limits for the Buyer Address - Street field (BT-50) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.","status":"WARNING"},{"type":"WARNING","code":"BR-KSA-F-06-C25","category":"KSA","message":"[BR-KSA-F-06-C25] - Field character limits for the Bu...
      message = '<p><strong>Simplified</strong></p><ul><li>Invoice result: Invoice sent to ZATCA. Integration status: Accepted</li><li>Credit note result: Invoice sent to ZATCA. Integration status: Accepted</li><li>Debit note result: Invoice sent to ZATCA. Integration status: Accepted</li></ul><p>Please check Error Log <a href="http://demoapp.site/app/error-log/679">679</a> for ZATCA responses</p><p><strong>Standard</strong></p><ul><li>Invoice result: Invoice sent to ZATCA. Integration status: Accepted with warnings</li><li>Credit note result: Invoice sent to ZATCA. Integration status: Accepted with warnings</li><li>Debit note result: Invoice sent to ZATCA. Integration status: Accepted with warnings</li></ul><p>Please check Error Log <a href="http://demoapp.site/app/error-log/680">680</a> for ZATCA responses</p>'
      error_log = <ErrorLog: 681>
      error_link = '<a href="http://demoapp.site/app/error-log/681">681</a>'
builtins.TypeError: msgprint() got an unexpected keyword argument 'realtime'

**Comment by mhaggag** [comment]
Hello,

We'll need some more details on the exact nature of the problem.

* Which environment is this? Simulation or production?
* What are the different app versions? (`bench version` from CLI or `Help -> About` on Desk)

**Comment by alaalsalam** [comment]
I am using Simulation  and frappe version 14. Is there a problem with that?

![image](https://github.com/user-attachments/assets/776bd738-ff1b-4b93-b848-eec81017e020)

**Comment by alaalsalam** [comment]
![image](https://github.com/user-attachments/assets/c02cc7a7-d9fc-4dbf-b387-c338aaeffc55)

**Comment by alaalsalam** [comment]
Ok I will upgrade to v15, but I am facing another problem in version 15 explained in the ticket after this I hope you can solve it, I am waiting

**Comment by mhaggag** [comment]
No worries. I'll close this issue and we can continue investigating the v15 issue.
