### ISSUE TITLE
perform compliance checks

### ISSUE THREAD

**Issue by hassan-youssef** [lavaloon-eg/ksa_compliance#181]
Invoice Result: Invoice sent to ZATCA. Integration status: Accepted with warnings
{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[{"type":"WARNING","code":"BR-CL-14","category":"EN_16931","message":"Country codes in an invoice MUST be coded using ISO code list 3166-1","status":"WARNING"}],"errorMessages":[],"status":"WARNING"},"reportingStatus":"REPORTED","clearanceStatus":null,"qrSellertStatus":null,"qrBuyertStatus":null}
Credit Note Result: Invoice sent to ZATCA. Integration status: Accepted with warnings
{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[{"type":"WARNING","code":"BR-CL-14","category":"EN_16931","message":"Country codes in an invoice MUST be coded using ISO code list 3166-1","status":"WARNING"}],"errorMessages":[],"status":"WARNING"},"reportingStatus":"REPORTED","clearanceStatus":null,"qrSellertStatus":null,"qrBuyertStatus":null}
Debit Note Result: Invoice sent to ZATCA. Integration status: Accepted with warnings
{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[{"type":"WARNING","code":"BR-CL-14","category":"EN_16931","message":"Country codes in an invoice MUST be coded using ISO code list 3166-1","status":"WARNING"}],"errorMessages":[],"status":"WARNING"},"reportingStatus":"REPORTED","clearanceStatus":null,"qrSellertStatus":null,"qrBuyertStatus":null}

**Comment by mhaggag** [comment]
Please double check the [country code](https://lavaloon.com/wiki/system-configuration-nbsp;#Country-Doctype)

**Comment by omarashrafsarhan** [comment]
As no further details or updates have been provided, I will proceed with closing this issue. If you still need assistance, please feel free to reopen the issue or create a new one with the required details.
