### ISSUE TITLE
when create sales invoice by education app got this error

### ISSUE THREAD

**Issue by amerwals** [lavaloon-eg/ksa_compliance#183]
I got this message when create sales invoice by education app, i add 

{"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[],"errorMessages":[{"type":"ERROR","code":"BR-KSA-49","category":"KSA","message":"[BR-KSA-49]- **If the tax exemption reason code (BT-121) is equal to VATEX-SA-EDU or VATEX-SA-HEA, then the other buyer ID (BT-46) is mandatory and must be national ID (BT-46-1 = NAT).","status":"ERROR"}**

note: i add fields in sales invoice for national id and tax exemption reason.
is there any solutions to fix that?
your support is appreciated

**Comment by mhaggag** [comment]
Hello,

The buyer ID is added on the "Customer" document directly--can you try opening the customer and adding the national ID in the additional IDs? The app wouldn't know about any additional/custom fields you added (if I understand you correctly)

**Comment by omarashrafsarhan** [comment]
As no further details or updates have been provided, I will proceed with closing this issue. If you still need assistance, please feel free to reopen the issue or create a new one with the required details.
