### ISSUE TITLE
Rejected ( An unknown error occurred )

### ISSUE THREAD

**Issue by sammish** [lavaloon-eg/ksa_compliance#186]
Hi, Team 
please support 

https://www.loom.com/share/ce16bff44b364c3290b949f20bf95ad4

ERPNext: v15.45.4 (version-15)

Frappe Framework: v15.49.1 (version-15)

KSA Compliance: v0.39.4 (master)

![image](https://github.com/user-attachments/assets/cdb37b23-eae6-4b61-b8c6-5ceb28e2bc42)

![image](https://github.com/user-attachments/assets/b9945904-2573-4761-81e0-d5dd038399e4)

**Comment by sammish** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"><ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionURI>urn:oasis:names:specification:ubl:dsig:enveloped:xades</ext:ExtensionURI>
        <ext:ExtensionContent>
            <sig:UBLDocumentSignatures xmlns:sig="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2" xmlns:sac="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2">
                <sac:SignatureInformation> 
                    <cbc:ID>urn:oasis:names:specification:ubl:signature:1</cbc:ID>
                    <sbc:ReferencedSignatureID>urn:oasis:names:specification:ubl:signature:Invoice</sbc:ReferencedSignatureID>
                    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="signature">
                        <ds:SignedInfo>
                            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
                            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"/>
                            <ds:Reference Id="invoiceSignedData" URI="">
                                <ds:Transforms>
                                    <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                                        <ds:XPath>not(//ancestor-or-self::ext:UBLExtensions)</ds:XPath>
                                    </ds:Transform>
                                    <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                                        <ds:XPath>not(//ancestor-or-self::cac:Signature)</ds:XPath>
                                    </ds:Transform>
                                    <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                                        <ds:XPath>not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])</ds:XPath>
                                    </ds:Transform>
                                    <ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
                                </ds:Transforms>
                                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                                <ds:DigestValue>xFZ/wENUtkJ3Uo3ji7iKeAfvB7mKTlpIxTfQd1zkV88=</ds:DigestValue>
                            </ds:Reference>
                            <ds:Reference Type="http://www.w3.org/2000/09/xmldsig#SignatureProperties" URI="#xadesSignedProperties">
                                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                                <ds:DigestValue>ODBiNDhhMTViOTEzYzA5MjNjMzA1YWRkY2RjZDJjNDg1ZGVlZjc5ZGUyNmZlYmJkMmE1OTcyY2E4Yzg4MjIxMA==</ds:DigestValue>
                            </ds:Reference>
                        </ds:SignedInfo>
                        <ds:SignatureValue>MEUCIQCc03ICRZ+0KhzWncjHVMBrH/WyolBQvm0bahWaLDZt+gIgeDJKyuxOAr0R5ydNhxt4Nlj4EZXn/33BU5VDR3nC+kw=</ds:SignatureValue>
                        <ds:KeyInfo>
                            <ds:X509Data>
                                <ds:X509Certificate>LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzakNDQTRTZ0F3SUJBZ0lURVFBQU9BUEY5MEFqcy94Y1h3QUJBQUE0QXpBS0JnZ3Foa2pPUFFRREFqQmlNUlV3RXdZS0NaSW1pWlB5TEdRQkdSWUZiRzlqWVd3eEV6QVJCZ29Ka2lhSmsvSXNaQUVaRmdObmIzWXhGekFWQmdvSmtpYUprL0lzWkFFWkZnZGxlSFJuWVhwME1Sc3dHUVlEVlFRREV4SlFVbHBGU1U1V1QwbERSVk5EUVRRdFEwRXdIaGNOTWpRd01URXhNRGt4T1RNd1doY05Namt3TVRBNU1Ea3hPVE13V2pCMU1Rc3dDUVlEVlFRR0V3SlRRVEVtTUNRR0ExVUVDaE1kVFdGNGFXMTFiU0JUY0dWbFpDQlVaV05vSUZOMWNIQnNlU0JNVkVReEZqQVVCZ05WQkFzVERWSnBlV0ZrYUNCQ2NtRnVZMmd4SmpBa0JnTlZCQU1USFZSVFZDMDRPRFkwTXpFeE5EVXRNems1T1RrNU9UazVPVEF3TURBek1GWXdFQVlIS29aSXpqMENBUVlGSzRFRUFBb0RRZ0FFb1dDS2EwU2E5RklFclRPdjB1QWtDMVZJS1h4VTluUHB4MnZsZjR5aE1lank4YzAyWEpibERxN3RQeWRvOG1xMGFoT01tTm84Z3duaTdYdDFLVDlVZUtPQ0FnY3dnZ0lETUlHdEJnTlZIUkVFZ2FVd2dhS2tnWjh3Z1p3eE96QTVCZ05WQkFRTU1qRXRWRk5VZkRJdFZGTlVmRE10WldReU1tWXhaRGd0WlRaaE1pMHhNVEU0TFRsaU5UZ3RaRGxoT0dZeE1XVTBORFZtTVI4d0hRWUtDWkltaVpQeUxHUUJBUXdQTXprNU9UazVPVGs1T1RBd01EQXpNUTB3Q3dZRFZRUU1EQVF4TVRBd01SRXdEd1lEVlFRYURBaFNVbEpFTWpreU9URWFNQmdHQTFVRUR3d1JVM1Z3Y0d4NUlHRmpkR2wyYVhScFpYTXdIUVlEVlIwT0JCWUVGRVgrWXZtbXRuWW9EZjlCR2JLbzdvY1RLWUsxTUI4R0ExVWRJd1FZTUJhQUZKdktxcUx0bXF3c2tJRnpWdnBQMlB4VCs5Tm5NSHNHQ0NzR0FRVUZCd0VCQkc4d2JUQnJCZ2dyQmdFRkJRY3dBb1pmYUhSMGNEb3ZMMkZwWVRRdWVtRjBZMkV1WjI5MkxuTmhMME5sY25SRmJuSnZiR3d2VUZKYVJVbHVkbTlwWTJWVFEwRTBMbVY0ZEdkaGVuUXVaMjkyTG14dlkyRnNYMUJTV2tWSlRsWlBTVU5GVTBOQk5DMURRU2d4S1M1amNuUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Ed0dDU3NHQVFRQmdqY1ZCd1F2TUMwR0pTc0dBUVFCZ2pjVkNJR0dxQjJFMFBzU2h1MmRKSWZPK3huVHdGVm1oL3FsWllYWmhENENBV1FDQVJJd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3TUdDQ3NHQVFVRkJ3TUNNQ2NHQ1NzR0FRUUJnamNWQ2dRYU1CZ3dDZ1lJS3dZQkJRVUhBd013Q2dZSUt3WUJCUVVIQXdJd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMRS9pY2htbldYQ1VLVWJjYTN5Y2k4b3F3YUx2RmRIVmpRcnZlSTl1cUFiQWlBOWhDNE04amdNQkFEUFN6bWQydWlQSkE2Z0tSM0xFMDNVNzVlcWJDL3JYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=</ds:X509Certificate>
                            </ds:X509Data>
                        </ds:KeyInfo>
                        <ds:Object>
                            <xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Target="signature">
                                <xades:SignedProperties Id="xadesSignedProperties">
                                    <xades:SignedSignatureProperties>
                                        <xades:SigningTime>2024-12-14T14:18:30</xades:SigningTime>
                                        <xades:SigningCertificate>
                                            <xades:Cert>
                                                <xades:CertDigest>
                                                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                                                    <ds:DigestValue>YWMxMjk4MTBhNmExYzgyNTY3OTZjM2FmNWY0ODFmZTJjMTIxNWZlZjYxMzJhNTcyODZlOWM2NzBmNDZiMjdiMg==</ds:DigestValue>
                                                </xades:CertDigest>
                                                <xades:IssuerSerial>
                                                    <ds:X509IssuerName>CN=PRZEINVOICESCA4-CA, DC=extgazt, DC=gov, DC=local</ds:X509IssuerName>
                                                    <ds:X509SerialNumber>379112742831380471835263969587287663520528387</ds:X509SerialNumber>
                                                </xades:IssuerSerial>
                                            </xades:Cert>
                                        </xades:SigningCertificate>
                                    </xades:SignedSignatureProperties>
                                </xades:SignedProperties>
                            </xades:QualifyingProperties>
                        </ds:Object>
                    </ds:Signature>
                </sac:SignatureInformation>
            </sig:UBLDocumentSignatures>
        </ext:ExtensionContent>
    </ext:UBLExtension>
</ext:UBLExtensions>
    <cbc:ProfileID>reporting:1.0</cbc:ProfileID>
    <cbc:ID>10005</cbc:ID>
    <cbc:UUID>2e4a963b-417e-4804-aee2-e6733b5a3feb</cbc:UUID>
    <cbc:IssueDate>2024-12-14</cbc:IssueDate>
    <cbc:IssueTime>17:17:16</cbc:IssueTime>
    <cbc:InvoiceTypeCode name="0100000">388</cbc:InvoiceTypeCode>
    <cbc:DocumentCurrencyCode>SAR</cbc:DocumentCurrencyCode>
    <cbc:TaxCurrencyCode>SAR</cbc:TaxCurrencyCode>
    <cac:AdditionalDocumentReference>
        <cbc:ID>ICV</cbc:ID>
        <cbc:UUID>10</cbc:UUID>
    </cac:AdditionalDocumentReference>
    <cac:AdditionalDocumentReference>
        <cbc:ID>PIH</cbc:ID>
        <cac:Attachment>
            <cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain">g3leV1JEIOq8ombZN8CWgGXHmOofz+Y/OpCUSV+rjng=</cbc:EmbeddedDocumentBinaryObject>
        </cac:Attachment>
    </cac:AdditionalDocumentReference>
    <cac:AdditionalDocumentReference>
        <cbc:ID>QR</cbc:ID>
        <cac:Attachment>
            <cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain">AShOQVRJT05BTCBST1lBTCBGT1IgTUFUVFJFU1NFUyBBTkQgRElWQU5TAg8zMDA1MTI2MjQyMDAwMDMDEzIwMjQtMTItMTRUMTc6MTc6MTYEBjEyMDMuMAUGMTU2Ljg5Bix4Rlovd0VOVXRrSjNVbzNqaTdpS2VBZnZCN21LVGxwSXhUZlFkMXprVjg4PQdgTUVVQ0lRQ2MwM0lDUlorMEtoelduY2pIVk1CckgvV3lvbEJRdm0wYmFoV2FMRFp0K2dJZ2VESkt5dXhPQXIwUjV5ZE5oeHQ0TmxqNEVaWG4vMzNCVTVWRFIzbkMra3c9CFgwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAShYIprRJr0UgStM6/S4CQLVUgpfFT2c+nHa+V/jKEx6PLxzTZcluUOru0/J2jyarRqE4yY2jyDCeLte3UpP1R4</cbc:EmbeddedDocumentBinaryObject>
        </cac:Attachment>
</cac:AdditionalDocumentReference><cac:Signature>
      <cbc:ID>urn:oasis:names:specification:ubl:signature:Invoice</cbc:ID>
      <cbc:SignatureMethod>urn:oasis:names:specification:ubl:dsig:enveloped:xades</cbc:SignatureMethod>
</cac:Signature><cac:AccountingSupplierParty>
        <cac:Party>
                <cac:PartyIdentification>
                    <cbc:ID schemeID="CRN">2050033329</cbc:ID>
                </cac:PartyIdentification>
            <cac:PostalAddress>
                <cbc:StreetName>P.O. BOX 20100</cbc:StreetName>
                <cbc:BuildingNumber>3938</cbc:BuildingNumber>
                <cbc:CitySubdivisionName>Al Khobar</cbc:CitySubdivisionName>
                <cbc:CityName>Dammam</cbc:CityName>
                <cbc:PostalZone>20100</cbc:PostalZone>
                <cac:Country>
                    <cbc:IdentificationCode>sa</cbc:IdentificationCode>
                </cac:Country>
            </cac:PostalAddress>
                <cac:PartyTaxScheme>
                    <cbc:CompanyID>300512624200003</cbc:CompanyID>
                    <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
                </cac:PartyTaxScheme>
            <cac:PartyLegalEntity>
                <cbc:RegistrationName>NATIONAL ROYAL FOR MATTRESSES AND DIVANS</cbc:RegistrationName>
            </cac:PartyLegalEntity>
        </cac:Party>
    </cac:AccountingSupplierParty>
    <cac:AccountingCustomerParty>
        <cac:Party>
                <cac:PartyIdentification>
                    <cbc:ID schemeID="TIN">300543172800003</cbc:ID>
                </cac:PartyIdentification>
            <cac:PostalAddress>
                <cbc:StreetName>abqaiq</cbc:StreetName>
                <cbc:BuildingNumber>8544</cbc:BuildingNumber>
                <cbc:CitySubdivisionName>Al Khobar Al Janubiyah dist.</cbc:CitySubdivisionName>
                <cbc:CityName>AL KHOBAR</cbc:CityName>
                <cbc:PostalZone>20100</cbc:PostalZone>
                <cac:Country>
                    <cbc:IdentificationCode>sa</cbc:IdentificationCode>
                </cac:Country>
            </cac:PostalAddress>
            <cac:PartyTaxScheme>
                <cbc:CompanyID>300543172800003</cbc:CompanyID>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:PartyTaxScheme>
            <cac:PartyLegalEntity>
                <cbc:RegistrationName>MATTRESES WORLD</cbc:RegistrationName>
            </cac:PartyLegalEntity>
        </cac:Party>
    </cac:AccountingCustomerParty>
    <cac:Delivery>
        <cbc:ActualDeliveryDate>2024-12-14</cbc:ActualDeliveryDate>
    </cac:Delivery>
    <cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:AllowanceChargeReason>Discount</cbc:AllowanceChargeReason>
        <cbc:Amount currencyID="SAR">55.05</cbc:Amount>
            <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>15.0</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:TaxCategory>
    </cac:AllowanceCharge>
    <cac:TaxTotal>
        <cbc:TaxAmount currencyID="SAR">156.89</cbc:TaxAmount>
            <cac:TaxSubtotal>
                <cbc:TaxableAmount currencyID="SAR">1045.95</cbc:TaxableAmount>
                <cbc:TaxAmount currencyID="SAR">156.89</cbc:TaxAmount>
                <cac:TaxCategory>
                    <cbc:ID>S</cbc:ID>
                    <cbc:Percent>15.0</cbc:Percent>
                    <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
                </cac:TaxCategory>
            </cac:TaxSubtotal>
    </cac:TaxTotal>
    <cac:TaxTotal>
        <cbc:TaxAmount currencyID="SAR">156.89</cbc:TaxAmount>
    </cac:TaxTotal>
    <cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="SAR">1101.0</cbc:LineExtensionAmount>
        <cbc:TaxExclusiveAmount currencyID="SAR">1045.95</cbc:TaxExclusiveAmount>
        <cbc:TaxInclusiveAmount currencyID="SAR">1202.84</cbc:TaxInclusiveAmount>
        <cbc:AllowanceTotalAmount currencyID="SAR">55.05</cbc:AllowanceTotalAmount>
        <cbc:PayableRoundingAmount currencyID="SAR">0.16</cbc:PayableRoundingAmount>
        <cbc:PayableAmount currencyID="SAR">1203.0</cbc:PayableAmount>
    </cac:LegalMonetaryTotal>
    <cac:InvoiceLine>
        <cbc:ID>1</cbc:ID>
        <cbc:InvoicedQuantity unitCode="PCE">1.0</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="SAR">521.0</cbc:LineExtensionAmount>
        <cac:TaxTotal>
            <cbc:TaxAmount currencyID="SAR">74.24</cbc:TaxAmount>
            <cbc:RoundingAmount currencyID="SAR">595.24</cbc:RoundingAmount>
        </cac:TaxTotal>
        <cac:Item>
            <cbc:Name>Royal American Mattress 160 x 200 x 21</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>15.0</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="SAR">521.0</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="PCE">1.0</cbc:BaseQuantity>
        </cac:Price>
    </cac:InvoiceLine>
    <cac:InvoiceLine>
        <cbc:ID>2</cbc:ID>
        <cbc:InvoicedQuantity unitCode="PCE">1.0</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="SAR">580.0</cbc:LineExtensionAmount>
        <cac:TaxTotal>
            <cbc:TaxAmount currencyID="SAR">82.65</cbc:TaxAmount>
            <cbc:RoundingAmount currencyID="SAR">662.65</cbc:RoundingAmount>
        </cac:TaxTotal>
        <cac:Item>
            <cbc:Name>Royal Orthopedic Mattress 120 x 200</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>15.0</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="SAR">580.0</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="PCE">1.0</cbc:BaseQuantity>
        </cac:Price>
    </cac:InvoiceLine>
</Invoice>

**Comment by mhaggag** [comment]
Hello,

The values shown in the integration tab in ZATCA Business Settings appear to be inconsistent. The shown production request ID (30368) is the hard-coded request ID returned on the Sandbox environment, but the environment in the drop-down is "Production". My guess is that you onboarded on sandbox then switched to Production. If that's the case, please restart the onboarding process (Onboard, perform compliance, then get production CSID)

**Comment by sammish** [comment]
Yeah, thanks so much! We fixed it.
