### ISSUE TITLE
Accepted with warnings

### ISSUE THREAD

**Issue by sammish** [lavaloon-eg/ksa_compliance#188]
hello, team 

We have encountered the error 'Accepted with warnings.' How can we resolve it?

![image](https://github.com/user-attachments/assets/47ce11b8-bc92-4fcf-9eff-f4baa6d5741b)

**Comment by sammish** [comment]
@mhaggag

**Comment by BOTSolutions8686** [comment]
This is because the erpnext by default has all the country codes in small letters. Please navigate to country list - and open your desired country then change the country code from small letters to capital letters. 

Eg -  sa -> SA
