### ISSUE TITLE
Branch Configuration not found

### ISSUE THREAD

**Issue by EmkanDevs** [lavaloon-eg/ksa_compliance#197]
Go the following error:
![AnyDesk_xgiC7lRZmI](https://github.com/user-attachments/assets/db5e360b-83c2-43e8-98ac-8406d4e43b36)

Checked the Settings and couldn't find the option.
![opera_7ltgGGjgjN](https://github.com/user-attachments/assets/f5f09fb5-2ae1-4661-9738-78f41257b6d8)

**Comment by omarashrafsarhan** [comment]
Hello,

Please provide us with the app version.

Check in the seller id tab it there is a checkbox "enable_branch_configuration"

**Comment by EmkanDevs** [comment]
The latest version v0.41.1

**Comment by omarashrafsarhan** [comment]
If the server is self-hosted, please ensure that the 'bench migrate' command has been executed, as this might resolve the issue.

If the issue persists or the server is not self-hosted, kindly provide additional details, including the steps to reproduce the issue, to help us investigate further.

**Comment by EmkanDevs** [comment]
Thank you very much. Issue resolved.
The issue was with migration as suggested.

**Comment by omarashrafsarhan** [comment]
You're welcome! I’m glad to hear the issue has been resolved. I will proceed with closing this issue. If you encounter any further concerns, feel free to reach out.
