### ISSUE TITLE
Isuue when install app

### ISSUE THREAD

**Issue by ahmad18189** [lavaloon-eg/ksa_compliance#34]
using 

https://github.com/lavaloon-eg/ksa_compliance.git --branch develop 

branch tested 

develop

main

error 

FileNotFoundError: [Errno 2] No such file or directory: '/home/frappe/frappe-bench/apps/ksa_compliance/setup.py'

**Comment by ahmad18189** [comment]
suggested file content 

`from setuptools import setup, find_packages

with open("requirements.txt") as f:
        install_requires = f.read().strip().split("\n")

# get version from __version__ variable in ksa_compliance/__init__.py
from ksa_compliance import __version__ as version

setup(
        name="ksa_compliance",
        version=version,
        description="KSA zatca phase 2",
        author="lavaloon.com",
        author_email="info@lavaloon.com",
        packages=find_packages(),
        zip_safe=False,
        include_package_data=True,
        install_requires=install_requires
)


`

**Comment by mhaggag** [comment]
Hello, Ahmad. Thanks for reporting.

`ksa_compliance` runs only on frappe 15, which ditched `setup.py` in favor of `pyproject.toml`. Please refer to [Migrating to version 15: Removal of setup.py](https://github.com/frappe/frappe/wiki/Migrating-to-Version-15#removal-of-setuppy)

If you encountered this error on a 15 bench, can you please share the bench version (`bench --version`) as well as app versions? (`bench version`)

**Comment by mhaggag** [comment]
I'm closing this on the assumption that it was a v14 bench. Please let me know if you still run into issues on v15.
