### ISSUE TITLE
Installation Error Self Hosting

### ISSUE THREAD

**Issue by omareldars** [lavaloon-eg/ksa_compliance#63]
On running the first command I get this error

![localization error](https://github.com/lavaloon-eg/ksa_compliance/assets/36465949/f5af495b-8f22-4ccc-81f7-6b4a0f6afa42)

**Comment by mhaggag** [comment]
Can you try replacing the `git@...` SSH repo URL with the HTTPS URL?

```
bench get-app https://github.com/lavaloon-eg/ksa_compliance.git
```
