### ISSUE TITLE
Fatoora Simulation Portal

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#68]
Hello,

I have three invoices accepted by zatca. but nothing in fatoora simulation portal/E-invoicing statistics . Is there any error?

![image](https://github.com/lavaloon-eg/ksa_compliance/assets/94270898/6f2cde95-37c8-431a-8210-4db5156fb6bc)

**Comment by mhaggag** [comment]
Hello,

We're not sure if the simulation portal is updated periodically (every X hours) or at all. We've seen similar behavior when onboarding customers on the simulation portal the past couple of days. I searched the [Developer Community](https://zatca1.discourse.group/) and found [this post](https://zatca1.discourse.group/t/why-are-the-submitted-invoices-not-showing-up-in-the-zatca-e-invoicing-statistics/403) which claims there's a delay of up to 48 hours. I'm not sure if this is true and up to date, but it's worth waiting a day or two and checking back again.

**Comment by mhaggag** [comment]
Hello, were there any updated statistics on the Fatoora simulation dashboard?

**Comment by saud-2** [comment]
So far same thing, there are no statistics. I read that it can sometimes take up to two weeks to appear in ZATCA portal.

**Comment by mhaggag** [comment]
I'm closing this for now since it seems to be a ZATCA issue or limitation.
