### ISSUE TITLE
POS Receipt 

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#69]
Dears,
No print format and QR Image for POS Receipt compatible with ZATCA Requirements.

**Comment by saud-2** [comment]
Standard ERPNext V14 covered ZATCA phase one and there is QR image for each POS Receipt. Anther QR image generated when closing the shift and issued consolidated invoice.

**Comment by mhaggag** [comment]
I think it's possible to support Phase 1 QR since it doesn't include signature and the like. @omarashrafsarhan Can you please look into this? Do we have everything we need for phase 1 QR?

For phase 2 QR, the proper QR needs to be generated and signed from the POS invoice, which requires a bunch of work.

**Comment by mhaggag** [comment]
This is now available on `master` after merging `0.23.0` from `develop` (it was introduced in `0.22.0`)

**Comment by saud-2** [comment]
> This is now available on `master` after merging `0.23.0` from `develop` (it was introduced in `0.22.0`)

Thank you for your reply . What about phase 2 any update ?

**Comment by mhaggag** [comment]
> > This is now available on `master` after merging `0.23.0` from `develop` (it was introduced in `0.22.0`)
> 
> Thank you for your reply . What about phase 2 any update ?

It's still in the roadmap, but I'm not sure whether we're committed to a certain date. @Ahmed-M-Fawzy should know more.

**Comment by saud-2** [comment]
> For phase 2 QR, the proper QR needs to be generated and signed from the POS invoice, which requires a bunch of work.

Maybe this is for standard tax invoice but simplified tax invoice is similar to Phase one because the zatca requirement is to reporting within 24 hours not clearance . correct me if I'm wrong.

**Comment by mhaggag** [comment]
This is currently under review in #111 and will go through testing next.

**Comment by saud-2** [comment]
good news.
Thank you

**Comment by omarashrafsarhan** [comment]
Fixed in version 0.32.0

**Comment by mhaggag** [comment]
This is still under testing in the develop branch and undergoing fixes. Reopening until it's stable and merged into master.

**Comment by mhaggag** [comment]
This is now available on master as part of 0.32.2

**Comment by saud-2** [comment]
Thank you and appreciate your efforts.

**Comment by Ahmed-M-Fawzy** [comment]
Welcome, @saud-2. We appreciate your efforts and the valuable insights you've provided to enhance our product and user experience. We would like to invite you to a meeting or call at your earliest convenience to get to know you better and introduce you to our team. If this works for you, please share your email or contact me at Ahmed.Fawzy@lavaloon.com.

**Comment by saud-2** [comment]
My pleasure to contact you, I will do so soon.
