### ISSUE TITLE
Error While Submitting Sales Invoice

### ISSUE THREAD

**Issue by osman-yasser** [lavaloon-eg/ksa_compliance#74]
This Error Appear to me when I submit Sales Invoice

![image](https://github.com/user-attachments/assets/59bbf8ac-3e50-4633-aa25-08790d83cc27)

**Comment by mhaggag** [comment]
Hello, Osman.

This looks like the certificate doesn't exist, meaning the production CSID wasn't generated (or the generated files were removed from the `sites/` directory in the bench). We'll improve detection of this case to give a better error message.

**Comment by osman-yasser** [comment]
The Issue was solved after completed **Perform Compliance Check** and **Get Production CSID**
