### ISSUE TITLE
Error When press button Perform Compliance Check in ZATCA Business Settings DocType

### ISSUE THREAD

**Issue by osman-yasser** [lavaloon-eg/ksa_compliance#75]
When I press Button _Perform Compliance Check_ that was in **ZATCA Business Settings DocType**, I encounter the error in the image below:

![image](https://github.com/user-attachments/assets/83ad6090-0ee8-4775-b6cc-bc70cafe26f5)

![image](https://github.com/user-attachments/assets/64e2171a-3d35-4266-92b2-6a4ac1d97e76)

---

When I investigate what make this error, I found a peace of code on the action on button click in js:

![image](https://github.com/user-attachments/assets/a68803ab-e5c5-4472-bb62-038f0438d288)

The code make a frappe.prompt and build its fields based on some condition, _simplified_ and **standard**.
Since, I chosen Type of Business Transactions to be Standard Tax Invoices, the simplified field never shown:

![image](https://github.com/user-attachments/assets/0f8ddea1-e5af-44a9-b159-8e5446bdefbe)

![image](https://github.com/user-attachments/assets/afb213d7-b265-4c3c-a14f-714a593a3ba7)

---
So, the value object will never have simplified_customer_id and will be undefined, consequently, the parameter simplified_customer_id in python whitelist method will never passed and this error appear

![image](https://github.com/user-attachments/assets/c843de35-15e1-4a89-83cc-9a8305d13f90)

---

**Comment by mhaggag** [comment]
Thanks for the report and the excellent investigation and write-up.

There's a [fix for this](https://github.com/lavaloon-eg/ksa_compliance/commit/772766dd611faf823b4879c48312809670eff620) currently on the dev branch, as part of 0.21.1, among other fixes but they're still under test. I'll keep you posted when it's approved and merged.

In the mean time, if you're trying on a development or test clone of your instance, you can switch to the dev branch to see if you run into other issues.

**Comment by osman-yasser** [comment]
That is right choose **Let the system decide (both)** and the error solved :)
---
But there is an error appear when the invoice was is **_sign_** process

```json
Invoice Result: Invoice sent to ZATCA. Integration status: Rejected
{
    "validationResults": {
        "infoMessages": [
            {
                "type": "INFO",
                "code": "XSD_ZATCA_VALID",
                "category": "XSD validation",
                "message": "Complied with UBL 2.1 standards in line with ZATCA specifications",
                "status": "PASS"
            }
        ],
        "warningMessages": [],
        "errorMessages": [
            {
                "type": "ERROR",
                "code": "GENERAL",
                "category": "BUSINESS_RULES",
                "message": "Unable to execute Business Rules validation ->",
                "status": "ERROR"
            },
            {
                "type": "ERROR",
                "code": "certificate-permissions",
                "category": "CERTIFICATE_ERRORS",
                "message": "Production CSID does not cover Simplified documents",
                "status": "ERROR"
            }
        ],
        "status": "ERROR"
    },
    "reportingStatus": "NOT_REPORTED",
    "clearanceStatus": null,
    "qrSellertStatus": null,
    "qrBuyertStatus": null
}
Credit Note Result: Invoice sent to ZATCA. Integration status: Rejected
{
    "validationResults": {
        "infoMessages": [
            {
                "type": "INFO",
                "code": "XSD_ZATCA_VALID",
                "category": "XSD validation",
                "message": "Complied with UBL 2.1 standards in line with ZATCA specifications",
                "status": "PASS"
            }
        ],
        "warningMessages": [],
        "errorMessages": [
            {
                "type": "ERROR",
                "code": "GENERAL",
                "category": "BUSINESS_RULES",
                "message": "Unable to execute Business Rules validation ->",
                "status": "ERROR"
            },
            {
                "type": "ERROR",
                "code": "certificate-permissions",
                "category": "CERTIFICATE_ERRORS",
                "message": "Production CSID does not cover Simplified documents",
                "status": "ERROR"
            }
        ],
        "status": "ERROR"
    },
    "reportingStatus": "NOT_REPORTED",
    "clearanceStatus": null,
    "qrSellertStatus": null,
    "qrBuyertStatus": null
}
Debit Note Result: Invoice sent to ZATCA. Integration status: Rejected
{
    "validationResults": {
        "infoMessages": [
            {
                "type": "INFO",
                "code": "XSD_ZATCA_VALID",
                "category": "XSD validation",
                "message": "Complied with UBL 2.1 standards in line with ZATCA specifications",
                "status": "PASS"
            }
        ],
        "warningMessages": [],
        "errorMessages": [
            {
                "type": "ERROR",
                "code": "GENERAL",
                "category": "BUSINESS_RULES",
                "message": "Unable to execute Business Rules validation ->",
                "status": "ERROR"
            },
            {
                "type": "ERROR",
                "code": "certificate-permissions",
                "category": "CERTIFICATE_ERRORS",
                "message": "Production CSID does not cover Simplified documents",
                "status": "ERROR"
            }
        ],
        "status": "ERROR"
    },
    "reportingStatus": "NOT_REPORTED",
    "clearanceStatus": null,
    "qrSellertStatus": null,
    "qrBuyertStatus": null
}
error
Comments
```
---
How can fix this error, I press **Perform Compliance Check**, fulfilled the dialog and submit

**Comment by mhaggag** [comment]
I haven't seen these errors before, but "Production CSID does not cover Simplified documents" could possibly mean the compliance CSID was generated from a CSR that only targeted standard tax invoices. The CSR includes a field defining what type of invoices will be generated, whether standard, simplified, or both. I'm assuming these errors are the results of using the CSR previously generated when the setting was "Standard".

Since we've changed it to  "Let the system decide", please try generating a new CSR (through the "Onboard" button) and then perform the compliance checks again.

**Comment by mhaggag** [comment]
0.21.1 was merged into master, which includes a fix to the initial report.

**Comment by osman-yasser** [comment]
Thanks :)
