### ISSUE TITLE
Server Error While checking Compliance 

### ISSUE THREAD

**Issue by RAhmed-Dev** [lavaloon-eg/ksa_compliance#80]
While checking Compliant I am getting this server error on local setup.

![WhatsApp Image 2024-08-02 at 16 51 25_2e6dcfbd](https://github.com/user-attachments/assets/893633f3-7f1c-4a79-916d-1ed52c942beb)

I have configured the Additional ID's in the Customer.

**Comment by mhaggag** [comment]
Hello. Does this happen as soon as you press the "Perform compliance checks" button, or after picking the customers in the pop-up dialog? Does the customer have a VAT registration number added, or just additional IDs?

**Comment by RAhmed-Dev** [comment]
hello, 

This happens when I try to select a Simplified Tax Customer and system shows this error. This customer does have Tax ID setup.

![image](https://github.com/user-attachments/assets/cb08fe79-21da-4d3c-9e31-568aa3e4a7a7)
 
App Version:
![image](https://github.com/user-attachments/assets/67afe6b3-550d-4980-bf8f-2fd2dd0c0dc1)

**Comment by Yazan01H** [comment]
I face the same problem as soon as I click on **perform compliance checks** what is the solution

**Comment by mhaggag** [comment]
> hello,
> 
> This happens when I try to select a Simplified Tax Customer and system shows this error. This customer does have Tax ID setup.

This looks to be a bug in the query filter for customers. It looks like there's an edge case that's not handled properly resulting in the SQL error. I'll look into it and  get back to you.

Note that the pop-up dialog has query filters configured to fetch customers without VAT information as "Simplified Customers" (for simplified tax invoices) and those with VAT information as "Standard Customers" (for standard tax invoices). Although the filter currently uses the custom field "VAT Registration Number" (`custom_vat_registration_number`) instead of the standard tax ID field.

**Comment by saud-2** [comment]
Erpnext version 14 is not supported by app. Maybe this is the reason of error.

**Comment by RAhmed-Dev** [comment]
I found a user manual video for this app config. 

So it does support v14 and v15.

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://m.youtube.com/watch%3Fv%3DyrB77VQvLiU&ved=2ahUKEwjR_PrCv-WHAxVTRvEDHe7VAwAQtwJ6BAgQEAE&usg=AOvVaw2QbfV_bsVly0tCmHv4l_Ia

**Comment by Ahmed-M-Fawzy** [comment]
> I found a user manual video for this app config.
> 
> So it does support v14 and v15.
> 
> https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://m.youtube.com/watch%3Fv%3DyrB77VQvLiU&ved=2ahUKEwjR_PrCv-WHAxVTRvEDHe7VAwAQtwJ6BAgQEAE&usg=AOvVaw2QbfV_bsVly0tCmHv4l_Ia

The video referenced was created using ERPNext version 15. The application does not support earlier versions, such as 14 or 13. Therefore, please upgrade ERPNext to version 15 first, and then install the application.

**Comment by RAhmed-Dev** [comment]
@Ahmed-M-Fawzy I have tried with V15, 

now I am getting this error. 

![image](https://github.com/user-attachments/assets/35b395b4-216f-4017-bd69-4723c2abd07c)


Version details:
![image](https://github.com/user-attachments/assets/dda2cdb0-0557-466b-98de-eb201abc0356)

**Comment by mhaggag** [comment]
That looks to be an error message from the ZATCA SDK when validating the company location passed in the CSR configuration. We use the company address for that. Can you share what the address looks like in the "Seller Details" tab?

You can also check logs/zatca.log to see the CSR details we send to the ZATCA SDK. Look for `csr.location.address`

**Comment by Ahmed-M-Fawzy** [comment]
[surprised]     Ahmed Fawzy reacted to your message:
________________________________

**Comment by RAhmed-Dev** [comment]
@mhaggag @Ahmed-M-Fawzy 
Thank you Both, you have been a great help. 

The issue was indeed with the address line 1. I remove the special character, and now its is working fine, 
![image](https://github.com/user-attachments/assets/252f29c7-5a12-48d2-899a-a1632c1a6c8e)

This app is working well on erpnext v15.

I got this error, but this is related to customer Information, I will correct that and try again. 
Thanks for your support.
