### ISSUE TITLE
Failed to generate CSR 

### ISSUE THREAD

**Issue by alaalsalam** [lavaloon-eg/ksa_compliance#83]
![Screenshot from 2024-08-12 14-00-57](https://github.com/user-attachments/assets/a7fa7d0b-2235-4599-92b4-12f2b4b58fd7)

Failed to generate CSR
invalid serial number, serial number should be in regular expression format (1-...|2-...|3-....)

![image](https://github.com/user-attachments/assets/e4c3cd97-7c49-48ba-a69d-8cc4934d4cef)

**Comment by mhaggag** [comment]
What's the value of `Company Unit Serial`? It has to be in a specific format as shown in the description below it.

![image](https://github.com/user-attachments/assets/51ab8184-27a3-4dd7-ba75-e7bed2d47c01)
