### ISSUE TITLE
Pre-payment validation warnings in generated XML

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#99]
When I perform compliance checks get this warning 

Standard Compliance Check Result
method
Error
Invoice Result: Invoice sent to ZATCA. Integration status: Accepted with warnings
{
  "status": null,
  "invoice_hash": null,
  "cleared_invoice": null,
  "warnings": [
    {
      "category": "KSA",
      "code": "BR-KSA-80",
      "message": " The Pre-Paid amount (BT-113) must be equal to the sum total of the Prepayment VAT category Taxable Amount (KSA-31) and the Prepayment VAT Category Tax Amount (KSA-32)."
    }
  ],
  "errors": []
}

**Comment by mhaggag** [comment]
There was an SDK update that added some validation around pre-payment; we don't support pre-payment yet, but we had some parts of it in place. These parts are causing the warning. We've fixed this problem in the `develop` branch but it's still pending testing.

**Comment by mhaggag** [comment]
This was fixed in 0.28.0 on the develop branch and is now available in 0.30.2 on the master branch

**Comment by saud-2** [comment]
Thanks.
